#!/bin/bash
head "$1"
adresar=$(dirname "$1")
adresar2="${adresar##*/}"
case "$adresar/" in
*"TIC-80/"*) core="tic80_libretro";;
*"LowresNX/"*) core="lowresnx_libretro";;
*"WASM-4/"*) core="wasm4_libretro";;
*"PICO-8/"*) core="pico8 -run";;
*"Voxatron/"*) core="vox";;
*"archive:ni-roms/roms/Arduboy Inc - Arduboy.zip/"*) core="arduous_libretro";;
*"archive:tosec-main/Arduboy/Arduboy/Games/[HEX]/"*) core="arduous_libretro";;
*"archive:mame-sl/mame-sl/uzebox.zip/"*) core="mame uzebox -cart";;
*"archive:tosec-main/8-Bit Productions/Commander X16/Games/[IMG]/"*) core="x16emu"; ext="img";;
*"archive:tosec-main/8-Bit Productions/Commander X16/Games/[PRG]/"*) core="x16emu"; ext="prg";;
*"archive:all_vircon32_roms_and_media/all_vircon32_roms_and_media/"*) core="vircon32_libretro";;
*"archive:mame-sl/mame-sl/chip8_quik.zip/"*) core="mame d6800 -quik";;
*"https://www.atarimania.com/roms/Atari-2600-VCS-ROM-Collection.zip/"*) core="stella_libretro";;
*"archive:ni-roms/roms/Atari - 2600.zip/"*) core="stella_libretro";;
*"archive:tosec-main/Atari/2600 & VCS/Games/"*) core="stella_libretro";;
*"archive:tosec-main/Atari/2600 & VCS/Homebrew/Games/[BIN]/"*) core="stella_libretro";;
*"archive:tosec-main/Atari/2600 & VCS/Applications/"*) core="stella_libretro";;
*"archive:tosec-main/Atari/2600 & VCS/Educational/"*) core="stella_libretro";;
*"archive:mame-sl/mame-sl/a2600.zip/"*) core="mame a2600 -cart";;
*"archive:mame-sl/mame-sl/a2600_cass.zip/"*) core="mame a2600 scharger -cass";;
*"archive:ni-roms/roms/Atari - 5200.zip/"*) core="a5200_libretro";;
*"archive:tosec-main/Atari/5200/Games/"*) core="a5200_libretro";;
*"archive:tosec-main/Atari/5200/Homebrew/Games/"*) core="a5200_libretro";;
*"archive:tosec-main/Atari/5200/Applications/"*) core="a5200_libretro";;
*"archive:mame-sl/mame-sl/a5200.zip/"*) core="mame a5200 -cart";;
*"archive:ni-roms/roms/Atari - 7800 (BIN).zip/"*) core="prosystem_libretro";;
*"archive:tosec-main/Atari/7800/Games/"*) core="prosystem_libretro";;
*"archive:tosec-main/Atari/7800/Homebrew/Games/"*) core="prosystem_libretro";;
*"archive:tosec-main/Atari/7800/Applications/"*) core="prosystem_libretro";;
*"archive:mame-sl/mame-sl/a7800.zip/"*) core="mame a7800 -cart";;
*"archive:ni-roms/roms/Atari - Jaguar (J64).zip/"*) core="virtualjaguar_libretro";;
*"archive:tosec-main/Atari/Jaguar/Games/[J64]/"*) core="virtualjaguar_libretro";;
*"archive:mame-sl/mame-sl/jaguar.zip/"*) core="mame jaguar -cart";;
*"archive:atari-jaguarcd-redump/"*) core="bigpemu"; ext="cue";;
*"archive:non-redump_atari-jaguar-cd/"*) core="bigpemu"; ext="cdi";;
*"archive:ni-roms/roms/Atari - Lynx (LYX).zip/"*) core="mednafen_lynx_libretro";;
*"archive:tosec-main/Atari/Lynx/Games/[LNX]/"*) core="mednafen_lynx_libretro";;
*"archive:mame-sl/mame-sl/lynx.zip/"*) core="mame lynx -cart"; ext="bin";;
*"archive:ni-roms/roms/Atari - 8-bit Family.zip/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Games/[ATR]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Games/[ATX]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Games/[BIN]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Games/[CAS]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Games/[XEX]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Applications/[ATR]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Applications/[BIN]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Applications/[CAS]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Applications/[XEX]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Educational/[ATR]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Educational/[BIN]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Educational/[CAS]/"*) core="atari800_libretro";;
*"archive:tosec-main/Atari/8bit/Educational/[XEX]/"*) core="atari800_libretro";;
*"archive:mame-sl/mame-sl/a800.zip/"*) core="mame a800 -cart1";;
*"archive:mame-sl/mame-sl/a800_flop.zip/"*) core="mame a800 -flop1";;
*"archive:mame-sl/mame-sl/xegs.zip/"*) core="mame xegs -cart";;
*"archive:ni-roms/roms/Atari - ST.zip/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Games/[ST]/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Games/[STX]/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Applications/[ST]/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Applications/[STX]/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Educational/[ST]/"*) core="hatari_libretro";;
*"archive:tosec-main/Atari/ST/Educational/[STX]/"*) core="hatari_libretro";;
*"archive:mame-sl/mame-sl/st_flop.zip/"*) core="mame st -flop";;
*"archive:tosec-main/Apple/1/Games/"*) core="mame apple1 -cass";;
*"archive:tosec-main/Apple/1/Applications/"*) core="mame apple1 -cass";;
*"archive:mame-sl/mame-sl/apple1.zip/"*) core="mame apple1 -cass";;
*"archive:tosec-main/Apple/II/Games/[DSK]/"*) core="mame apple2ee -flop1";;
*"archive:tosec-main/Apple/II/Games/[WOZ]/"*) core="mame apple2ee -flop1";;
*"archive:tosec-main/Apple/II/Educational/[DSK]/"*) core="mame apple2ee -flop1";;
*"archive:tosec-main/Apple/II/Educational/[WOZ]/"*) core="mame apple2ee -flop1";;
*"archive:tosec-main/Apple/II/Applications/[DSK]/"*) core="mame apple2ee -flop1";;
*"archive:tosec-main/Apple/II/Applications/[WOZ]/"*) core="mame apple2ee -flop1";;
*"archive:mame-sl/mame-sl/apple2_flop_clcracked.zip/"*) core="mame apple2ee -flop1";;
*"archive:mame-sl/mame-sl/apple2_flop_misc.zip/"*) core="mame apple2ee -flop1";;
*"archive:mame-sl/mame-sl/apple2_flop_orig.zip/"*) core="mame apple2ee -flop1";;
*"archive:mame-sl/mame-sl/apple2_cass.zip/"*) core="mame apple2ee -cass";;
*"archive:tosec-main/Apple/IIGS/Games/[2MG]/"*) core="mame apple2gs -flop3";;
*"archive:tosec-main/Apple/IIGS/Educational/[2MG]/"*) core="mame apple2gs -flop3";;
*"archive:tosec-main/Apple/IIGS/Applications/[2MG]/"*) core="mame apple2gs -flop3";;
*"archive:mame-sl/mame-sl/apple2gs_flop_clcracked.zip/"*) core="mame apple2gs -flop3";;
*"archive:mame-sl/mame-sl/apple2gs_flop_misc.zip/"*) core="mame apple2gs -flop3";;
*"archive:mame-sl/mame-sl/apple2gs_flop_orig.zip/"*) core="mame apple2gs -flop3";;
*"archive:tosec-main/Apple/III/Games/"*) core="mame apple3 -flop1";;
*"archive:tosec-main/Apple/III/Applications/[DSK]/"*) core="mame apple3 -flop1";;
*"archive:tosec-main/Apple/III/Applications/[PO]/"*) core="mame apple3 -flop1";;
*"archive:tosec-main/Apple/III/Collections/WAP III SIG Public Domain Library/"*) core="mame apple3 -flop1";;
*"archive:mame-sl/mame-sl/apple3.zip/"*) core="mame apple3 -flop1";;
*"archive:tosec-main/Apple/Lisa/Applications/[IMAGE]/"*) core="mame lisa -flop1";;
*"archive:tosec-main/Apple/Lisa/Applications/[A2R]/"*) core="mame lisa -flop1";;
*"archive:mame-sl/mame-sl/lisa.zip/"*) core="mame lisa -flop1";;
*"archive:mame-sl/mame-sl/mac_flop.zip/"*) core="mame macse -flop1";;
*"archive:mame-sl/mame-sl/mac_flop_orig.zip/"*) core="mame macse -flop1";;
*"archive:mame-sl/mame-sl/mac_flop_clcracked.zip/"*) core="mame macse -flop1";;
*"archive:mame-sl/mame-sl/mac_hdflop.zip/"*) core="mame macse -flop1";;
*"MAME/Software List CHDs (merged)/mac_cdrom/"*) core="mame macse -cdrom";;
*"archive:mame-software-list-chds-2/mac_hdd/"*) core="mame macse -hard";;
*"archive:tosec-main/Apple/Macintosh/Games/[DSK]/"*) core="mame macse -flop1";;
*"archive:tosec-main/Apple/Macintosh/Games/[IMG]/"*) core="mame macse -flop1";;
*"archive:mame-sl/mame-sl/zx80_cass.zip/"*) core="mame zx80 -autoboot_command 'W\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sinclair/ZX81/Games/[P]/"*) core="81_libretro";;
*"archive:tosec-main/Sinclair/ZX81/Applications/[P]/"*) core="81_libretro";;
*"archive:mame-sl/mame-sl/zx81_cass.zip/"*) core="mame zx81 -autoboot_command 'J\"\"\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[DSK]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[SCL]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[TAP]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[TRD]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[TZX]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Games/[Z80]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Educational/[TAP]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Educational/[TZX]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Educational/[Z80]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Applications/[TAP]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Applications/[TZX]/"*) core="fuse_libretro";;
*"archive:tosec-main/Sinclair/ZX Spectrum/Applications/[Z80]/"*) core="fuse_libretro";;
*"archive:mame-sl/mame-sl/spectrum_cass.zip/"*) core="mame spectrum -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"FinalBurn Neo/spectrum/"*) core="fuse_libretro";;
*"archive:mame-sl/mame-sl/timex_cass.zip/"*) core="mame tc2068 -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/spectrum_betadisc_flop.zip/"*) core="mame pentagon -flop";;
*"archive:mame-sl/mame-sl/spectrum_flop_opus.zip/"*) core="mame spec128 -flop";;
*"archive:mame-sl/mame-sl/spectrum_cart.zip/"*) core="mame specpls3 -cart";;
*"archive:mame-sl/mame-sl/spectrum_mgt_flop.zip/"*) core="mame spec128 -flop";;
*"archive:mame-sl/mame-sl/specpls3_flop.zip/"*) core="mame specpls3 -flop";;
*"archive:tosec-main/Sinclair/QL/Demos/[MDV]/"*) core="mame ql -autoboot_command 'BOOT\n' -autoboot_delay 5 -utap1"; ext="mdv";;
*"archive:mame-sl/mame-sl/ql_cass.zip/"*) core="mame ql -autoboot_command 'BOOT\n' -autoboot_delay 5 -utap1";;
*"archive:mame-sl/mame-sl/ql_cart.zip/"*) core="mame ql -cart";;
*"archive:mame-sl/mame-sl/ql_flop.zip/"*) core="mame ql -exp trump -flop";;
*"archive:mame-sl/mame-sl/z88_cart.zip/"*) core="mame z88 -cart1";;
*"archive:tosec-main/Amstrad/CPC/Games/[DSK]/"*) core="cap32_libretro";;
*"archive:tosec-main/Amstrad/CPC/Games/[CDT]/"*) core="cap32_libretro";;
*"archive:tosec-main/Amstrad/CPC/Games/[SNA]/"*) core="cap32_libretro";;
*"archive:tosec-main/Amstrad/CPC/Applications/[DSK]/"*) core="cap32_libretro";;
*"archive:mame-sl/mame-sl/cpc_cass.zip/"*) core="mame cpc464 -autoboot_command 'RUN\"\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/cpc_flop.zip/"*) core="mame cpc6128 -flop1";;
*"archive:tosec-main/Amstrad/GX4000/Games/"*) core="cap32_libretro";;
*"archive:mame-sl/mame-sl/gx4000.zip/"*) core="mame gx4000 -cart";;
*"archive:mame-sl/mame-sl/pcw.zip/"*) core="mame pcw8256 -flop";;
*"archive:tosec-main/Commodore/PET/Games/[PRG]/"*) core="vice_xpet_libretro";;
*"archive:mame-sl/mame-sl/pet_cass.zip/"*) core="mame pet2001n -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/pet_flop.zip/"*) core="mame pet2001n -flop1";;
*"archive:mame-sl/mame-sl/pet_rom.zip/"*) core="mame pet2001n -rom";;
*"archive:ni-roms/roms/Commodore - Plus-4.zip/"*) core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Games/[PRG]/"*) core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Games/[TAP]/"*) core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Utilities/[PRG]/"*) core="vice_xplus4_libretro";;
*"archive:mame-sl/mame-sl/plus4_cart.zip/"*) core="mame c16 -cart";;
*"archive:mame-sl/mame-sl/plus4_flop.zip/"*) core="mame c16 -flop";;
*"archive:mame-sl/mame-sl/plus4_cass.zip/"*) core="mame c16 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/vic10.zip/"*) core="mame vic10";;
*"archive:ni-roms/roms/Commodore - VIC-20.zip/"*) core="vice_xvic_libretro";;
*"archive:tosec-main/Commodore/VIC20/Games/[CRT]/Singlepart/"*) core="vice_xvic_libretro";;
*"archive:tosec-main/Commodore/VIC20/Games/[D64]/"*) core="vice_xvic_libretro";;
*"archive:tosec-main/Commodore/VIC20/Games/[PRG]/Singlepart/"*) core="vice_xvic_libretro";;
*"archive:tosec-main/Commodore/VIC20/Games/[TAP]/"*) core="vice_xvic_libretro";;
*"archive:tosec-main/Commodore/VIC20/Applications/[PRG]/Singlepart/"*) core="vice_xvic_libretro";;
*"archive:mame-sl/mame-sl/vic1001_cart.zip/"*) core="mame vic20 -cart";;
*"archive:mame-sl/mame-sl/cbm2_cart.zip/"*) core="mame cbm610 -cart";;
*"archive:mame-sl/mame-sl/cbm2_flop.zip/"*) core="mame cbm610 -autoboot_command 'DLOAD\"\"*\"\"\nRUN\n' -autoboot_delay 5 -flop1";;
*"archive:ni-roms/roms/Commodore - Commodore 64.zip/"*) core="vice_x64sc_libretro";;
*"archive:ni-roms/roms/Commodore - Commodore 64 (PP).zip/"*) core="vice_x64sc_libretro";;
*"archive:ni-roms/roms/Commodore - Commodore 64 (Tapes).zip/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Adventure/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Arcade/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Boulder Dash/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Cards/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Gambling/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Misc/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Racing/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Shoot'em Up/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Simulation/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Sports/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Games/Strategy/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Educational/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Educational/[PRG]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Educational/[T64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Applications/[D64]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Applications/[PRG]/"*) core="vice_x64sc_libretro";;
*"archive:tosec-main/Commodore/C64/Applications/[T64]/"*) core="vice_x64sc_libretro";;
*"archive:mame-sl/mame-sl/c64_cart.zip/"*) core="mame c64 -cart";;
*"archive:mame-sl/mame-sl/c64_cass.zip/"*) core="mame c64 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/c64_flop_orig.zip/"*) core="mame c64 -flop";;
*"archive:mame-sl/mame-sl/c64_flop_misc.zip/"*) core="mame c64 -flop";;
*"archive:tosec-main/Commodore/C128/Games/[D64]/"*) core="vice_x128_libretro";;
*"archive:tosec-main/Commodore/C128/Games/[PRG]/"*) core="vice_x128_libretro";;
*"archive:tosec-main/Commodore/C128/Applications/[D64]/"*) core="vice_x128_libretro";;
*"archive:mame-sl/mame-sl/c128_cart.zip/"*) core="mame c128 -cart";;
*"archive:mame-sl/mame-sl/c128_flop.zip/"*) core="mame c128 -flop";;
*"archive:mame-sl/mame-sl/c128_rom.zip/"*) core="mame c128 -rom";;
*"archive:ni-roms/roms/Commodore - Amiga.zip/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Games/[ADF]/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Games/[Unofficial IPF]/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Games/Public Domain/[ADF]/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Games/SPS/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Educational/[ADF]/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Applications/[ADF]/"*) core="puae_libretro";;
*"archive:tosec-main/Commodore/Amiga/Applications/Public Domain/[ADF]/"*) core="puae_libretro";;
*"archive:mame-sl/mame-sl/amiga_flop.zip/"*) core="mame a500 -flop";;
*"archive:mame-sl/mame-sl/amigaecs_flop.zip/"*) core="mame a600 -flop";;
*"archive:mame-sl/mame-sl/amigaocs_flop.zip/"*) core="mame a500 -flop";;
*"archive:mame-sl/mame-sl/amigaaga_flop.zip/"*) core="mame a1200 -flop";;
*"MAME/Software List CHDs (merged)/amiga_cd/"*) core="mame a500 -cdrom";;
*"archive:noaen-redump-commodore-amiga-cd/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga/CD/Games/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga/CD/Applications/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga/CD/Multimedia/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:noaen-redump-commodore-amiga-cd32/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CD32/Games/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CD32/Applications/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CD32/Educational/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CD32/Multimedia/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:mame-software-list-chds-2/cd32/"*) core="mame cd32 -cdrm";;
*"archive:ni-roms/roms/Nintendo - Nintendo Entertainment System (Headered).zip/"*) core="nestopia_libretro";;
*"archive:tosec-main/Nintendo/Famicom & Entertainment System/Games/[NES]/"*) core="nestopia_libretro";;
*"archive:mame-sl/mame-sl/nes.zip/"*) core="mame nes -cart";;
*"archive:mame-sl/mame-sl/nes_ade.zip/"*) core="mame nes -cart";;
*"FinalBurn Neo/nes/"*) core="nestopia_libretro";;
*"archive:mame-sl/mame-sl/nes_ntbrom.zip/"*) core="mame nes -cart1 nes:nantbb -cart2";;
*"archive:mame-sl/mame-sl/famicom_cass.zip/"*) core="mame famicom famibs30 -cass";;
*"archive:ni-roms/roms/Nintendo - Family Computer Disk System (FDS).zip/"*) core="nestopia_libretro";;
*"archive:tosec-main/Nintendo/Famicom Disk System/Games/[FDS]/"*) core="nestopia_libretro";;
*"archive:mame-sl/mame-sl/famicom_flop.zip/"*) core="mame fds -flop";;
*"FinalBurn Neo/fds/"*) core="nestopia_libretro";;
*"archive:ni-roms/roms/Nintendo - Super Nintendo Entertainment System.zip/"*) core="snes9x_libretro";;
*"archive:tosec-main/Nintendo/Super Famicom & Super Entertainment System/Games/"*) core="snes9x_libretro";;
*"archive:mame-sl/mame-sl/snes.zip/"*) core="mame snes -cart";;
*"FinalBurn Neo/snes/"*) core="snes9x_libretro";;
*"archive:mame-sl/mame-sl/snes_strom.zip/"*) core="mame snes -cart1 snes:sufami -cart2";;
*"archive:mame-sl/mame-sl/snes_bspack.zip/"*) core="mame snes -cart";;
*"T-En Collection/Nintendo - Super Famicom - MSU1/"*) core="snes9x_libretro";;
*"T-En Collection/Nintendo - Super Famicom - MSU1 [roms only]/"*) core="snes9x_libretro";;
*"archive:ni-roms/roms/Nintendo - Satellaview.zip/"*) core="snes9x_libretro";;
*"archive:ni-roms/roms/Nintendo - Sufami Turbo.zip/"*) core="snes9x_libretro";;
*"archive:tosec-main/Nintendo/Sufami Turbo/Games/"*) core="snes9x_libretro";;
*"archive:ni-roms/roms/Nintendo - Game Boy.zip/"*) core="mesen-s_libretro";;
*"archive:tosec-main/Nintendo/Game Boy/Games/"*) core="mesen-s_libretro";;
*"archive:mame-sl/mame-sl/gameboy.zip/"*) core="mame supergb -cart";;
*"T-En Collection/Nintendo - Super Famicom - MSU1/"*) core="bsnes_libretro";;
*"T-En Collection/Nintendo - Super Famicom - MSU1 [roms only]/"*) core="bsnes_libretro";;
*"archive:ni-roms/roms/Nintendo - Nintendo 64 (ByteSwapped).zip/"*) core="mupen64plus_next_libretro";;
*"archive:tosec-main/Nintendo/64/Games/"*) core="mupen64plus_next_libretro";;
*"archive:mame-sl/mame-sl/n64.zip/"*) core="mame n64 -cart";;
*"archive:mame-sl/mame-sl/n64dd.zip/"*) core="mame n64dd -hard";;
*"archive:tosec-main/Nintendo/64DD/Games/[BIN]/"*) core="mame n64dd -hard";;
*"Redump/Nintendo - GameCube - NKit RVZ [zstd-19-128k]/"*) core="dolphin_libretro"; ext="rvz";;
*"archive:tosec-iso-namco-sega-nintendo/Nintendo/GameCube/Games/"*) core="dolphin_libretro"; ext="iso";;
*"No-Intro/Unofficial - Nintendo - Wii (Digital) (Deprecated) (WAD)/"*) core="dolphin_libretro"; ext="wad";;
*"Redump/Nintendo - Wii - NKit RVZ [zstd-19-128k]/"*) core="dolphin_libretro"; ext="rvz";;
*"archive:ni-roms/roms/Nintendo - Pokemon Mini.zip/"*) core="pokemini_libretro";;
*"archive:tosec-main/Nintendo/Pokemon Mini/Games/"*) core="pokemini_libretro";;
*"archive:mame-sl/mame-sl/pokemini.zip/"*) core="mame pokemini -cart";;
*"archive:ni-roms/roms/Nintendo - Virtual Boy.zip/"*) core="mednafen_vb_libretro";;
*"archive:tosec-main/Nintendo/Virtual Boy/Games/"*) core="mednafen_vb_libretro";;
*"archive:mame-sl/mame-sl/vboy.zip/"*) core="mame vboy -cart";;
*"archive:ni-roms/roms/Nintendo - Game Boy.zip/"*) core="sameboy_libretro";;
*"archive:tosec-main/Nintendo/Game Boy/Games/"*) core="sameboy_libretro";;
*"archive:mame-sl/mame-sl/gameboy.zip/"*) core="mame gameboy -cart";;
*"archive:ni-roms/roms/Nintendo - Game Boy Color.zip/"*) core="sameboy_libretro";;
*"archive:tosec-main/Nintendo/Game Boy Color/Games/[GBC]/"*) core="sameboy_libretro";;
*"archive:mame-sl/mame-sl/gbcolor.zip/"*) core="mame gbcolor -cart";;
*"archive:ni-roms/roms/Nintendo - Game Boy Advance.zip/"*) core="mgba_libretro";;
*"archive:tosec-main/Nintendo/Game Boy Advance/Games/"*) core="mgba_libretro";;
*"archive:mame-sl/mame-sl/gba.zip/"*) core="mame gba -cart";;
*"archive:mame-sl/mame-sl/gba_ereader.zip/"*) core="mame gba -cart";;
*"No-Intro/Nintendo - Nintendo DS (Decrypted)/"*) core="melonds_libretro";;
*"archive:ni-roms/roms/Nintendo - Nintendo DS (Download Play).zip/"*) core="melonds_libretro";;
*"archive:tosec-main/Nintendo/DS/Games/"*) core="melonds_libretro";;
*"archive:ni-roms/roms/Nintendo - Nintendo DSi (Decrypted).zip/"*) core="melondsds_libretro";;
*"archive:tosec-main/Nintendo/DSi/Games/"*) core="melondsds_libretro";;
*"No-Intro/Nintendo - Nintendo 3DS (Decrypted)/"*) core="citra_libretro"; ext="3ds";;
*"Redump/Nintendo - Wii U - WUX/"*) core="cemu -g"; ext="wux";;
*"archive:tosec-main/Sega/Visual Memory System/Games/"*) core="mame svmu -quik";;
*"archive:mame-sl/mame-sl/svmu.zip/"*) core="mame svmu -quik";;
*"archive:ni-roms/roms/Sega - SG-1000.zip/"*) core="gearsystem_libretro";;
*"archive:tosec-main/Sega/Game 1000/Games/"*) core="gearsystem_libretro";;
*"archive:mame-sl/mame-sl/sg1000.zip/"*) core="mame sg1000 -cart";;
*"FinalBurn Neo/sg1000/"*) core="gearsystem_libretro";;
*"archive:tosec-main/Sega/Computer 3000/Applications/"*) core="mame sc3000 -cart";;
*"archive:tosec-main/Sega/Computer 3000/Educational/"*) core="mame sc3000 -cart";;
*"archive:tosec-main/Sega/Computer 3000/Games/[WAV]/"*) core="mame sc3000 -autoboot_command 'LOAD\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/sc3000_cart.zip/"*) core="mame sc3000 -cart";;
*"archive:mame-sl/mame-sl/sc3000_cass.zip/"*) core="mame sc3000 -autoboot_command 'LOAD\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/sf7000.zip/"*) core="mame sf7000 -flop";;
*"archive:mame-sl/mame-sl/segaai.zip/"*) core="mame segaai -card";;
*"archive:ni-roms/roms/Sega - Master System - Mark III.zip/"*) core="gearsystem_libretro";;
*"archive:tosec-main/Sega/Mark III & Master System/Games/"*) core="gearsystem_libretro";;
*"archive:mame-sl/mame-sl/sms.zip/"*) core="mame sms -cart";;
*"FinalBurn Neo/sms/"*) core="gearsystem_libretro";;
*"archive:ni-roms/roms/Sega - Mega Drive - Genesis.zip/"*) core="genesis_plus_gx_libretro";;
*"archive:tosec-main/Sega/Mega Drive & Genesis/Games/[BIN]/"*) core="genesis_plus_gx_libretro";;
*"archive:mame-sl/mame-sl/megadriv.zip/"*) core="mame megadriv -cart";;
*"FinalBurn Neo/megadrive/"*) core="genesis_plus_gx_libretro";;
*"archive:mame-sl/mame-sl/megatech.zip/"*) core="mame megatech -cart";;
*"T-En Collection/Sega - Mega Drive - MSU-MD/"*) core="genesis_plus_gx_libretro"; ext="md";;
*"archive:ni-roms/roms/Sega - PICO.zip/"*) core="picodrive_libretro";;
*"archive:tosec-main/Sega/Pico/Educational/"*) core="picodrive_libretro";;
*"archive:mame-sl/mame-sl/pico.zip/"*) core="mame pico -cart";;
*"archive:ni-roms/roms/Sega - Beena.zip/"*) core="mame beena -cart";;
*"archive:tosec-main/Sega/Advanced Pico Beena/Educational/"*) core="mame beena -cart";;
*"archive:mame-sl/mame-sl/sega_beena_cart.zip/"*) core="mame beena -cart";;
*"archive:ni-roms/roms/Sega - 32X.zip/"*) core="picodrive_libretro";;
*"archive:tosec-main/Sega/32X/Games/"*) core="picodrive_libretro";;
*"archive:mame-sl/mame-sl/32x.zip/"*) core="mame 32x -cart";;
*"archive:sega-mega-cd-sega-cd-redump/"*) core="picodrive_libretro"; ext="cue";;
*"archive:tosec-iso-sega/Mega-CD & Sega CD/CD/Games/[ISO]/"*) core="picodrive_libretro"; ext="cue";;
*"archive:non-redump_sega-mega-cd_sega-cd/"*) core="picodrive_libretro"; ext="cue";;
*"MAME/Software List CHDs (merged)/megacd/"*) core="mame segacd -cdrm";;
*"archive:redump.sega_saturn/"*) core="yabasanshiro_libretro"; ext="cue";;
*"archive:non-redump_sega-saturn/"*) core="yabasanshiro_libretro"; ext="cue";;
*"archive:tosec-iso-sega/Saturn/Games/[ISO]/"*) core="yabasanshiro_libretro"; ext="cue";;
*"MAME/Software List CHDs (merged)/saturn/"*) core="mame saturn -cdrm";;
*"archive:mame-sl/mame-sl/stv.zip/"*) core="mame stvbios";;
*"archive:sega-dreamcast-redump/"*) core="flycast_libretro"; ext="cue";;
*"archive:non-redump_sega-dreamcast/"*) core="flycast_libretro"; ext="gdi";;
*"archive:tosec-iso-sega/Dreamcast/Games/US/"*) core="flycast_libretro"; ext="gdi";;
*"archive:tosec-iso-sega/Dreamcast/Games/PAL/"*) core="flycast_libretro"; ext="gdi";;
*"archive:tosec-iso-sega/Dreamcast/Games/JP/"*) core="flycast_libretro"; ext="gdi";;
*"MAME/Software List CHDs (merged)/dc/"*) core="mame dc -cdrm";;
*"archive:m2emu1.1a/Sega Model 2 Emu 1.1a and Full Romset/Model 2 Romset (Merged)/"*) core="mame";;
*"archive:segamodel3/ROMs/"*) core="mame";;
*"archive:ni-roms/roms/Sega - Game Gear.zip/"*) core="gearsystem_libretro";;
*"archive:tosec-main/Sega/Game Gear/Games/"*) core="gearsystem_libretro";;
*"archive:mame-sl/mame-sl/gamegear.zip/"*) core="mame gamegear -cart";;
*"FinalBurn Neo/gamegear/"*) core="gearsystem_libretro";;
*"archive:tosec-main/Sony/PocketStation/Various/"*) core="mame pockstat -cart";;
*"archive:mame-sl/mame-sl/smc777.zip/"*) core="mame smc777 -flop1";;
*"Redump/Sony - PlayStation/"*) core="pcsx_rearmed_libretro"; ext="cue";;
*"archive:non-redump_sony_playstation/"*) core="pcsx_rearmed_libretro"; ext="cue";;
*"MAME/Software List CHDs (merged)/psx/"*) core="mame psu -cdrm";;
*"Redump/Sony - PlayStation 2/"*) core="pcsx2"; ext="iso";;
*"archive:non-redump_sony_playstation2_part1/"*) core="pcsx2"; ext="iso";;
*"archive:non-redump_sony_playstation2_part2/"*) core="pcsx2"; ext="iso";;
*"archive:non-redump_sony_playstation2_part3/"*) core="pcsx2"; ext="iso";;
*"archive:playstation-portable-redump/"*) core="ppsspp_libretro"; ext="iso";;
*"archive:non-redump_sony_playstation_portable/"*) core="ppsspp_libretro"; ext="iso";;
*"No-Intro/Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)/"*) core="ppsspp_libretro"; ext="iso";;
*"archive:tosec-iso-sony/PlayStation Portable/Games/[ISO]/"*) core="ppsspp_libretro"; ext="iso";;
*"eXo/eXoDOS/Full Release/eXo/eXoDOS/"*) core="dosbox_pure_libretro";;
*"archive:tosec-main/IBM/PC Compatibles/Games/[IMG]/"*) core="dosbox_pure_libretro";;
*"archive:tosec-main/IBM/PC Compatibles/Applications/[IMG]/"*) core="dosbox_pure_libretro";;
*"archive:tosec-main/IBM/PC Compatibles/Educational/[IMG]/"*) core="dosbox_pure_libretro";;
*"archive:tosec-iso-ibm/PC Compatibles/CD/Games/[ISO]/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1981/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1982/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1983/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1984/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1985/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1986/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1987/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1988/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1989/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/198x/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1990/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1991/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1992/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1993/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1994/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1995/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1996/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1997/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1998/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1999/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/199x/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/19xx/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2000/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2001/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2002/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2003/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2004/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2005/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2006/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2007/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2008/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2009/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2010/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2011/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2012/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2013/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2014/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2015/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2016/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2017/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2018/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2019/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2020/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2021/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2022/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2023/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2024/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2025/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1990/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1991/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1992/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1993/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1994/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1995/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1996/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1997/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1998/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/1999/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2000/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2001/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2003/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2006/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2016/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Images/CD/2018/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1983/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1984/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1985/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1986/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1987/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1988/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1989/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1990/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1991/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1992/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1993/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1994/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1995/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1996/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1997/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1998/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/1999/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/199x/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/19xx/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2000/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2001/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2002/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2003/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2004/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2005/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2006/"*) core="dosbox_pure_libretro";;
*"Total DOS Collection/Applications/Files/2009/"*) core="dosbox_pure_libretro";;
*"archive:mame-sl/mame-sl/ibm5150.zip/"*) core="mame ibm5150 -hard1 ibm5150_hdd:freedos13_8086";;
*"archive:mame-sl/mame-sl/ibm5170.zip/"*) core="mame ibm5170 -hard1 ibm5170_hdd:freedos13";;
*"archive:mame-software-list-chds-2/ibm5170_cdrom/"*) core="mame ibm5170 -cdrom";;
*"archive:mame-sl/mame-sl/ibm5170_cdrom.zip/"*) core="mame ibm5170 -cdrom";;
*"archive:mame-software-list-chds-2/ibm5170_hdd/"*) core="mame ibm5170 -hard";;
*"archive:mame-sl/mame-sl/ibmpcjr_cart.zip/"*) core="mame ibmpcjr";;
*"archive:mame-sl/mame-sl/ibmpcjr_flop.zip/"*) core="mame ibmpcjr -hard1 ibm5150_hdd:freedos13_8086";;
*"archive:ni-roms/roms/Microsoft - MSX.zip/"*) core="bluemsx_libretro";;
*"archive:tosec-main/MSX/MSX/Games/[CAS]/"*) core="bluemsx_libretro";;
*"archive:tosec-main/MSX/MSX/Games/[DSK]/"*) core="bluemsx_libretro";;
*"archive:tosec-main/MSX/MSX/Games/[ROM]/"*) core="bluemsx_libretro";;
*"archive:mame-sl/mame-sl/msx1_cart.zip/"*) core="mame expert11 -cart1";;
*"archive:mame-sl/mame-sl/msx1_cass.zip/"*) core="mame expert11 -autoboot_command 'RUN\"CAS:\"\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/msx1_flop.zip/"*) core="mame svi738 -flop";;
*"FinalBurn Neo/msx/"*) core="bluemsx_libretro";;
*"archive:ni-roms/roms/Microsoft - MSX2.zip/"*) core="bluemsx_libretro";;
*"archive:tosec-main/MSX/MSX2/Games/[DSK]/"*) core="bluemsx_libretro";;
*"archive:tosec-main/MSX/MSX2/Games/[ROM]/"*) core="bluemsx_libretro";;
*"archive:mame-sl/mame-sl/msx2_cart.zip/"*) core="mame hbf1xd -cart1";;
*"archive:mame-sl/mame-sl/msx2_flop.zip/"*) core="mame hbf1xd -flop";;
*"archive:mame-sl/mame-sl/msx2_cass.zip/"*) core="mame hbf1xd -autoboot_command 'RUN\"CAS:\"\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/MSX/MSX2+/Games/"*) core="bluemsx_libretro";;
*"archive:mame-sl/mame-sl/msx2p_cart.zip/"*) core="mame fsa1wsx -cart1";;
*"archive:mame-sl/mame-sl/msx2p_flop.zip/"*) core="mame fsa1wsx -flop";;
*"archive:tosec-main/MSX/TurboR/Games/"*) core="bluemsx_libretro";;
*"archive:mame-sl/mame-sl/msxr_flop.zip/"*) core="mame fsa1gt -flop1";;
*"archive:mame-sl/mame-sl/msxr_cart.zip/"*) core="mame fsa1gt -cart1";;
*"archive:mame-sl/mame-sl/studio2.zip/"*) core="mame studio2 -cart";;
*"archive:ni-roms/roms/Fairchild - Channel F.zip/"*) core="freechaf_libretro";;
*"archive:tosec-main/Fairchild/VES & Channel F/Games/"*) core="freechaf_libretro";;
*"archive:mame-sl/mame-sl/channelf.zip/"*) core="mame channelf -cart";;
*"FinalBurn Neo/channelf/"*) core="freechaf_libretro";;
*"archive:ni-roms/roms/GCE - Vectrex.zip/"*) core="vecx_libretro";;
*"archive:tosec-main/GCE/Vectrex/Games/"*) core="vecx_libretro";;
*"archive:mame-sl/mame-sl/vectrex.zip/"*) core="mame vectrex -cart";;
*"archive:ni-roms/roms/Magnavox - Odyssey 2.zip/"*) core="o2em_libretro";;
*"archive:tosec-main/Magnavox/Odyssey2/Games/"*) core="o2em_libretro";;
*"archive:mame-sl/mame-sl/videopac.zip/"*) core="mame videopac -cart";;
*"archive:ni-roms/roms/Philips - Videopac+.zip/"*) core="o2em_libretro";;
*"archive:tosec-main/Philips/Videopac+/Games/"*) core="o2em_libretro";;
*"archive:ni-roms/roms/Mattel - Intellivision.zip/"*) core="freeintv_libretro";;
*"archive:tosec-main/Mattel/Intellivision/Games/[BIN]/"*) core="freeintv_libretro";;
*"archive:mame-sl/mame-sl/intv.zip/"*) core="mame intv -cart";;
*"archive:mame-sl/mame-sl/intvecs.zip/"*) core="mame intvecs -cart";;
*"archive:ni-roms/roms/Coleco - ColecoVision.zip/"*) core="gearcoleco_libretro";;
*"archive:tosec-main/Coleco/ColecoVision/Games/"*) core="gearcoleco_libretro";;
*"archive:mame-sl/mame-sl/coleco.zip/"*) core="mame coleco -cart";;
*"FinalBurn Neo/coleco/"*) core="gearcoleco_libretro";;
*"archive:mame-sl/mame-sl/coleco_homebrew.zip/"*) core="mame coleco -cart";;
*"MAME/Software List ROMs (merged)/cassvisn_cart/"*) core="mame cassvisn";;
*"archive:ni-roms/roms/Epoch - Super Cassette Vision.zip/"*) core="emuscv_libretro";;
*"archive:tosec-main/Epoch/Super Cassette Vision/Games/"*) core="emuscv_libretro";;
*"archive:mame-sl/mame-sl/scv.zip/"*) core="mame scv -cart";;
*"archive:mame-sl/mame-sl/ctvboy.zip/"*) core="mame ctvboy -cart";;
*"archive:mame-sl/mame-sl/sv8000.zip/"*) core="mame sv8000 -cart";;
*"archive:ni-roms/roms/Bally - Astrocade.zip/"*) core="mame astrocde -cart";;
*"archive:tosec-main/Bally/Professional Arcade & Astrocade/Games/[BIN]/"*) core="mame astrocde -cart";;
*"archive:mame-sl/mame-sl/astrocde.zip/"*) core="mame astrocde -cart";;
*"archive:ni-roms/roms/APF - MP-1000.zip/"*) core="mame apfm1000 -cart";;
*"archive:tosec-main/APF/M-1000/Games/"*) core="mame apfm1000 -cart";;
*"archive:mame-sl/mame-sl/apfm1000.zip/"*) core="mame apfm1000 -cart";;
*"archive:mame-sl/mame-sl/apfimag_cass.zip/"*) core="mame apfimag -cass";;
*"archive:ni-roms/roms/VTech - CreatiVision.zip/"*) core="mame crvision -cart";;
*"archive:tosec-main/VTech/Laser 2001 & CreatiVision/Games/"*) core="mame crvision -cart";;
*"archive:mame-sl/mame-sl/crvision.zip/"*) core="mame crvision -cart";;
*"archive:ni-roms/roms/VTech - V.Smile.zip/"*) core="mame vsmile -cart";;
*"archive:tosec-main/VTech/V.Smile Motion/Games/[BIN]/"*) core="mame vsmile -cart";;
*"archive:mame-sl/mame-sl/vsmile_cart.zip/"*) core="mame vsmile -cart";;
*"archive:mame-sl/mame-sl/vsmilem_cart.zip/"*) core="mame vsmilem -cart";;
*"archive:mame-sl/mame-sl/vsmileb_cart.zip/"*) core="mame vsmileb -cart";;
*"archive:ni-roms/roms/Emerson - Arcadia 2001.zip/"*) core="mame arcadia -cart";;
*"archive:tosec-main/Emerson/Arcadia 2001/Games/"*) core="mame arcadia -cart";;
*"archive:mame-sl/mame-sl/arcadia.zip/"*) core="mame arcadia -cart";;
*"archive:mame-software-list-chds-2/hyperscan/"*) core="mame hyprscan -cdrom";;
*"archive:ni-roms/roms/Funtech - Super Acan.zip/"*) core="mame supracan -cart";;
*"archive:tosec-main/Funtech/Super A'can/Games/"*) core="mame supracan -cart";;
*"archive:mame-sl/mame-sl/supracan.zip/"*) core="mame supracan -cart";;
*"archive:ni-roms/roms/Interton - VC 4000.zip/"*) core="mame vc4000 -cart";;
*"archive:mame-sl/mame-sl/vc4000.zip/"*) core="mame vc4000 -cart";;
*"archive:tosec-main/Tsukuda Original/Othello Multivision/Games/"*) core="gearsystem_libretro";;
*"archive:mame-sl/mame-sl/vii.zip/"*) core="mame vii -cart";;
*"archive:mame-sl/mame-sl/unichamp.zip/"*) core="mame unichamp -cart";;
*"archive:mame-sl/mame-sl/entex_sag.zip/"*) core="mame sag -cart";;
*"archive:mame-sl/mame-sl/ekara_cart.zip/"*) core="mame ekara -cart";;
*"archive:mame-sl/mame-sl/videoart.zip/"*) core="mame videoart -cart";;
*"archive:mame-sl/mame-sl/pdp1_ptp.zip/"*) core="mame pdp1 -ptap1";;
*"archive:mame-sl/mame-sl/sol20_cass.zip/"*) core="mame sol20 -cass1";;
*"archive:tosec-main/Tandy Radio Shack/TRS-80 Model III/Games/[CMD]/"*) core="mame trs80m3 -quik";;
*"archive:tosec-main/Tandy Radio Shack/TRS-80 Model 4/Games/[CMD]/"*) core="mame trs80m3 -quik";;
*"archive:mame-sl/mame-sl/trs80_quik.zip/"*) core="mame trs80m3 -quik";;
*"archive:mame-sl/mame-sl/trs80_cass.zip/"*) core="mame trs80m3 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/trs80_flop.zip/"*) core="mame trs80m3 -flop1";;
*"archive:mame-sl/mame-sl/trs80m2.zip/"*) core="mame trs80m2 -flop1";;
*"archive:mame-sl/mame-sl/sorcerer_cart.zip/"*) core="mame sorcerer -cart";;
*"archive:mame-sl/mame-sl/sorcerer_cass.zip/"*) core="mame sorcerer -cart sorcerer_cart:basicpac -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 5 -cass1";;
*"archive:mame-sl/mame-sl/sorcerer_flop.zip/"*) core="mame sorcererd -flop1";;
*"archive:mame-sl/mame-sl/z80ne_cass.zip/"*) core="mame z80net -cass1";;
*"archive:mame-sl/mame-sl/z80ne_flop.zip/"*) core="mame z80netf -flop1";;
*"archive:mame-sl/mame-sl/osborne1.zip/"*) core="mame osborne1 -flop1";;
*"archive:mame-sl/mame-sl/jupace_cass.zip/"*) core="mame jupace -cass";;
*"archive:mame-sl/mame-sl/nascom_snap.zip/"*) core="mame nascom2 -dump1";;
*"archive:mame-sl/mame-sl/nascom_flop.zip/"*) core="mame nascom2 -flop1";;
*"archive:mame-sl/mame-sl/abc80_flop.zip/"*) core="mame abc80 -flop1";;
*"archive:mame-sl/mame-sl/abc80_cass.zip/"*) core="mame abc80 -cass";;
*"archive:mame-sl/mame-sl/abc80_rom.zip/"*) core="mame abc80 -cart";;
*"archive:mame-sl/mame-sl/kaypro.zip/"*) core="mame kaypro2x -flop1";;
*"archive:mame-sl/mame-sl/galaxy.zip/"*) core="mame galaxy -autoboot_command 'OLD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/special_cass.zip/"*) core="mame special -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/special_flop.zip/"*) core="mame specimx -flop1";;
*"archive:mame-sl/mame-sl/apogee.zip/"*) core="mame apogee -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/radio86_cass.zip/"*) core="mame radio86 -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mikrosha_cass.zip/"*) core="mame mikrosha -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/partner_cass.zip/"*) core="mame partner -cass";;
*"archive:mame-sl/mame-sl/partner_flop.zip/"*) core="mame partner -flop1";;
*"archive:mame-sl/mame-sl/korvet_flop.zip/"*) core="mame korvet -flop1";;
*"archive:tosec-main/Acorn/Atom/Games/[DSK]/"*) core="mame atom -flop1";;
*"archive:mame-sl/mame-sl/atom_flop.zip/"*) core="mame atom -flop1";;
*"archive:mame-sl/mame-sl/atom_rom.zip/"*) core="mame atom -cart";;
*"archive:mame-sl/mame-sl/atom_cass.zip/"*) core="mame atom -cass";;
*"archive:mame-sl/mame-sl/interact.zip/"*) core="mame interact -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/spc1000_cass.zip/"*) core="mame spc1000 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/EACA/EG2000 Colour Genie/Games/[CAS]/"*) core="mame cgenie -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/cgenie_cass.zip/"*) core="mame cgenie -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"archive:tosec-main/Dragon Data/Dragon/Games/[CAS]/"*) core="mame dragon64 -autoboot_command 'CLOAD\n' -autoboot_delay 4 -cass";;
*"archive:mame-sl/mame-sl/dragon_cass.zip/"*) core="mame dragon64 -autoboot_command 'CLOAD\n' -autoboot_delay 4 -cass";;
*"archive:mame-sl/mame-sl/dragon_flop.zip/"*) core="mame dragon64 -flop1";;
*"archive:mame-sl/mame-sl/dragon_cart.zip/"*) core="mame dragon64 -cart";;
*"archive:mame-sl/mame-sl/dragon_os9.zip/"*) core="mame dragon64 -flop1";;
*"archive:mame-sl/mame-sl/dragon_flex.zip/"*) core="mame dragon64 -flop1";;
*"archive:mame-sl/mame-sl/dgnalpha_flop.zip/"*) core="mame dragon64 -flop1";;
*"archive:tosec-main/Tangerine/Oric-1 & Oric Atmos/Games/[TAP]/"*) core="mame orica -autoboot_command 'CLOAD\"\"\n' -autoboot_delay 4 -cass";;
*"archive:mame-sl/mame-sl/oric1_cass.zip/"*) core="mame orica -autoboot_command 'CLOAD\"\"\n' -autoboot_delay 4 -cass";;
*"archive:mame-sl/mame-sl/camplynx_cass.zip/"*) core="mame lynx48k -autoboot_command 'mload\"\"\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/camplynx_flop.zip/"*) core="mame lynx128k -flop1";;
*"archive:mame-sl/mame-sl/orao.zip/"*) core="mame orao -cass";;
*"archive:mame-sl/mame-sl/vg5k.zip/"*) core="mame vg5k -cass";;
*"archive:mame-sl/mame-sl/pegasus_cart.zip/"*) core="mame pegasus -rom1";;
*"archive:mame-sl/mame-sl/juku.zip/"*) core="mame juku -flop1";;
*"archive:mame-sl/mame-sl/x07_cass.zip/"*) core="mame x07 -cass";;
*"archive:mame-sl/mame-sl/alice32.zip/"*) core="mame alice32 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/alice90.zip/"*) core="mame alice90 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Tandy Radio Shack/TRS-80 MC-10/Various/"*) core="mame mc10 -cass";;
*"archive:mame-sl/mame-sl/mc10.zip/"*) core="mame mc10 -cass";;
*"archive:mame-sl/mame-sl/phc25_cass.zip/"*) core="mame phc25 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/VTech/Laser 200/Games/[VZ]/"*) core="mame laser310 -dump";;
*"archive:tosec-main/VTech/Laser 200/Applications/"*) core="mame laser310 -dump";;
*"archive:tosec-main/VTech/Laser 310/Applications/"*) core="mame laser310 -dump";;
*"archive:mame-sl/mame-sl/vz_snap.zip/"*) core="mame laser310 -dump";;
*"archive:mame-sl/mame-sl/vz_cass.zip/"*) core="mame laser310 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"archive:tosec-main/Elektronika/BK-0011-411/Games/"*) core="bk_libretro";;
*"archive:tosec-main/Elektronika/BK-0010-0011M/Applications/"*) core="bk_libretro";;
*"archive:mame-sl/mame-sl/bk0010.zip/"*) core="mame bk0010 -cass";;
*"archive:mame-sl/mame-sl/pmd85_cass.zip/"*) core="mame pmd851 -autoboot_command 'MGLD 00\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/lviv.zip/"*) core="mame lviv -autoboot_command 'CLOAD \"\"\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mc1000_cass.zip/"*) core="mame mc1000 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/pecom_cass.zip/"*) core="mame pecom64 -autoboot_command 'PLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/spc1500_cass.zip/"*) core="mame spc1500 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/orion_flop.zip/"*) core="mame orion128 -flop1";;
*"archive:mame-sl/mame-sl/orion_cass.zip/"*) core="mame orion128 -cass";;
*"archive:mame-sl/mame-sl/vidbrain.zip/"*) core="mame vidbrain -cart";;
*"archive:mame-sl/mame-sl/super80_cass.zip/"*) core="mame super80 -cass";;
*"archive:mame-sl/mame-sl/super80_flop.zip/"*) core="mame super80r -flop1";;
*"archive:tosec-main/Acorn/BBC/Games/[SSD]/"*) core="mame bbcb -flop1";;
*"archive:mame-sl/mame-sl/bbcb_flop.zip/"*) core="mame bbcb -flop1";;
*"archive:mame-sl/mame-sl/bbcb_flop_orig.zip/"*) core="mame bbcb -flop1";;
*"archive:mame-sl/mame-sl/bbc_cass.zip/"*) core="mame bbcb -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/bbc_rom.zip/"*) core="mame bbcb -rom1";;
*"archive:mame-sl/mame-sl/bbcm_cart.zip/"*) core="mame bbcm -cart";;
*"archive:mame-sl/mame-sl/bbcm_flop.zip/"*) core="mame bbcm -flop1";;
*"archive:mame-sl/mame-sl/bbcmc_flop.zip/"*) core="mame bbcmc -flop1";;
*"archive:mame-sl/mame-sl/ti99_cart.zip/"*) core="mame ti99_4a";;
*"archive:mame-sl/mame-sl/mbee_cart.zip/"*) core="mame mbee -cart";;
*"archive:mame-sl/mame-sl/mbee_quik.zip/"*) core="mame mbee -quik";;
*"archive:mame-sl/mame-sl/mbee_flop.zip/"*) core="mame mbee56 -flop1";;
*"archive:mame-sl/mame-sl/m5_cart.zip/"*) core="mame m5 -cart1";;
*"archive:mame-sl/mame-sl/m5_cass.zip/"*) core="mame m5 -cart1 m5_cart:basici -autoboot_command 'CHAIN\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/aquarius_cart.zip/"*) core="mame aquarius -cart1";;
*"archive:mame-sl/mame-sl/aquarius_cass.zip/"*) core="mame aquarius -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Coleco/ColecoVision ADAM/Games/[DSK]/"*) core="mame adam -flop1";;
*"archive:tosec-main/Coleco/ColecoVision ADAM/Applications/[DSK]/"*) core="mame adam -flop1";;
*"archive:mame-sl/mame-sl/adam_flop.zip/"*) core="mame adam -flop1";;
*"archive:mame-sl/mame-sl/adam_cass.zip/"*) core="mame adam -cass";;
*"archive:mame-sl/mame-sl/adam_cart.zip/"*) core="mame adam -cart1";;
*"archive:tosec-main/Spectravideo/SVI-318 & SVI-328/Games/[BIN]/"*) core="bluemsx_libretro";;
*"archive:tosec-main/Spectravideo/SVI-318 & SVI-328/Various/[CAS]/"*) core="bluemsx_libretro";;
*"archive:mame-sl/mame-sl/svi318_cass.zip/"*) core="mame svi318 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mtx_cart.zip/"*) core="mame mtx512 -cart1";;
*"archive:mame-sl/mame-sl/mtx_cass.zip/"*) core="mame mtx512 -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mtx_flop.zip/"*) core="mame mtx512 -exp_ext sdxbas -flop1";;
*"archive:mame-sl/mame-sl/mtx_rom.zip/"*) core="mame mtx512 -rom";;
*"archive:mame-sl/mame-sl/pencil2.zip/"*) core="mame pencil2 -cart";;
*"archive:tosec-main/Acorn/Electron/Games/[UEF]/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"archive:tosec-main/Acorn/Electron/Applications/[UEF]/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"archive:tosec-main/Acorn/Electron/Educational/[UEF]/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/electron_cass.zip/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"archive:mame-sl/mame-sl/electron_flop.zip/"*) core="mame electron64 -flop";;
*"archive:mame-sl/mame-sl/electron_cart.zip/"*) core="mame electron64 -exp plus1 -cart";;
*"archive:mame-sl/mame-sl/electron_rom.zip/"*) core="mame electron64 -exp plus1 -rom";;
*"archive:tosec-main/Tomy/Tutor & Pyuuta/Games/"*) core="mame tutor -cart";;
*"archive:mame-sl/mame-sl/tutor.zip/"*) core="mame tutor -cart";;
*"archive:mame-sl/mame-sl/exl100.zip/"*) core="mame exl100 -cart";;
*"archive:mame-sl/mame-sl/compclr2_flop.zip/"*) core="mame compclr2 -flop1";;
*"archive:mame-sl/mame-sl/myvision.zip/"*) core="mame myvision -cart";;
*"archive:mame-sl/mame-sl/einstein.zip/"*) core="mame einstein -flop1";;
*"archive:mame-sl/mame-sl/kc_cass.zip/"*) core="mame kc85_4 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/kc_cart.zip/"*) core="mame kc85_4 -cart";;
*"archive:mame-sl/mame-sl/kc_flop.zip/"*) core="mame kc85_4 -flop1";;
*"archive:tosec-main/Videoton/TV-Computer/Games/[CAS]/"*) core="ep128emu_core_libretro";;
*"archive:mame-sl/mame-sl/tvc_flop.zip/"*) core="mame tvc64p -flop1";;
*"archive:mame-sl/mame-sl/tvc_cass.zip/"*) core="mame tvc64p -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/tvc_cart.zip/"*) core="mame tvc64p -cart";;
*"archive:ni-roms/roms/Bandai - Gundam RX-78.zip/"*) core="mame rx78 -cart";;
*"archive:tosec-main/Bandai/Gundam RX-78/Games/[BIN]/"*) core="mame rx78 -cart";;
*"archive:mame-sl/mame-sl/rx78_cart.zip/"*) core="mame rx78 -cart";;
*"archive:mame-sl/mame-sl/rx78_cass.zip/"*) core="mame rx78 basic -cass";;
*"archive:tosec-main/Tandy Radio Shack/TRS-80 Color Computer/Games/[ROM]/"*) core="mame coco3 -cart";;
*"archive:tosec-main/Tandy Radio Shack/TRS-80 Color Computer/Applications/[ROM]/"*) core="mame coco3 -cart";;
*"archive:mame-sl/mame-sl/coco_cart.zip/"*) core="mame coco3 -cart";;
*"archive:mame-sl/mame-sl/coco_flop.zip/"*) core="mame coco3 -flop1";;
*"archive:tosec-main/MGT/Sam Coupe/Games/[DSK]/"*) core="mame samcoupe -flop1";;
*"archive:mame-sl/mame-sl/samcoupe_flop.zip/"*) core="mame samcoupe -flop1";;
*"archive:mame-sl/mame-sl/samcoupe_cass.zip/"*) core="mame samcoupe -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Enterprise/64 & 128/Games/[BAS]/"*) core="ep128emu_core_libretro";;
*"archive:tosec-main/Enterprise/64 & 128/Games/[COM]/"*) core="ep128emu_core_libretro";;
*"archive:tosec-main/Enterprise/64 & 128/Games/[DTF]/"*) core="ep128emu_core_libretro";;
*"archive:tosec-main/Enterprise/64 & 128/Games/[Multipart]/"*) core="ep128emu_core_libretro";;
*"archive:mame-sl/mame-sl/ep64_flop.zip/"*) core="mame ep128 -flop";;
*"archive:mame-sl/mame-sl/ep64_cart.zip/"*) core="mame ep128 -cart";;
*"archive:mame-sl/mame-sl/ep64_cass.zip/"*) core="mame ep128 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/vector06_flop.zip/"*) core="mame vector06 -flop1";;
*"archive:mame-sl/mame-sl/socrates.zip/"*) core="mame socrates -cart";;
*"archive:tosec-main/Thomson/MO5/Games/[K7]/"*) core="theodore_libretro";;
*"archive:tosec-main/Thomson/MO6/Games/"*) core="theodore_libretro";;
*"archive:tosec-main/Thomson/TO7/Games/[K7]/"*) core="theodore_libretro";;
*"archive:tosec-main/Thomson/TO7/Games/[M7]/"*) core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[FD]/"*) core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[K7]/"*) core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[SAP]/"*) core="theodore_libretro";;
*"archive:mame-sl/mame-sl/mo5_cart.zip/"*) core="mame mo5 -cart";;
*"archive:mame-sl/mame-sl/mo5_cass.zip/"*) core="mame mo5 -autoboot_command 'RUN\"\"\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mo5_flop.zip/"*) core="mame mo5 -flop";;
*"archive:mame-sl/mame-sl/mo6_cass.zip/"*) core="mame mo6 -autoboot_command '2\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/mo6_flop.zip/"*) core="mame mo6 -flop";;
*"archive:mame-sl/mame-sl/to_flop.zip/"*) core="mame to8 -flop";;
*"archive:mame-sl/mame-sl/to7_cart.zip/"*) core="mame to7 -cart";;
*"archive:mame-sl/mame-sl/to7_cass.zip/"*) core="mame to7 -cart basic -autoboot_command '1\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/to8_cass.zip/"*) core="mame to8 -autoboot_command '2\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/mo5_qd.zip/"*) core="mame mo5 -flop";;
*"archive:mame-sl/mame-sl/to7_qd.zip/"*) core="mame to7 -flop";;
*"archive:mame-sl/mame-sl/rainbow.zip/"*) core="mame rainbow -flop1";;
*"archive:mame-sl/mame-sl/tiki100.zip/"*) core="mame tiki100 -flop1";;
*"archive:mame-sl/mame-sl/pro128_cass.zip/"*) core="mame pro128 -autoboot_command 'RUN\"CASS:\"\n' -autoboot_delay 8 -cass";;
*"archive:mame-sl/mame-sl/pro128_cart.zip/"*) core="mame pro128 -cart";;
*"archive:mame-sl/mame-sl/pro128_flop.zip/"*) core="mame pro128 -flop1";;
*"archive:mame-sl/mame-sl/pro128s_flop.zip/"*) core="mame pro128s -flop1";;
*"archive:tosec-main/Acorn/Archimedes/Games/[ADF]/"*) core="mame aa4401 -flop";;
*"archive:tosec-main/Acorn/Archimedes/Applications/[ADF]/"*) core="mame aa4401 -flop";;
*"archive:mame-sl/mame-sl/archimedes.zip/"*) core="mame aa4401 -flop";;
*"archive:mame-sl/mame-sl/pc6001_cart.zip/"*) core="mame pc6001 -cart1";;
*"MAME/Software List ROMs (merged)/pc6001_cass/"*) core="mame pc6001 -cass";;
*"MAME/Software List ROMs (merged)/pc6001mk2_cass/"*) core="mame pc6001mk2 -cass";;
*"archive:mame-sl/mame-sl/pc8001_flop.zip/"*) core="mame pc8001mk2sr -flop1";;
*"archive:mame-sl/mame-sl/pc8001mk2_flop.zip/"*) core="mame pc8001mk2sr -flop1";;
*"archive:mame-sl/mame-sl/pc8001mk2sr_flop.zip/"*) core="mame pc8001mk2sr -flop1";;
*"archive:tosec-main/NEC/PC-8801/Games/[D88]/"*) core="quasi88_libretro";;
*"archive:mame-sl/mame-sl/pc8801_flop.zip/"*) core="mame pc8801 -flop1";;
*"archive:mame-sl/mame-sl/pc8801_cass.zip/"*) core="mame pc8801 -cass";;
*"archive:tosec-main/NEC/PC-9801/Games/[FDD]/"*) core="np2kai_libretro";;
*"archive:mame-sl/mame-sl/pc98.zip/"*) core="mame pc9801 -flop1";;
*"archive:mame-software-list-chds-2/pc98_cd/"*) core="mame pc9821 -cdrm";;
*"archive:mame-sl/mame-sl/pc98_cd.zip/"*) core="mame pc9821 -cdrm";;
*"archive:tosec-main/NEC/PC-9821/Games/[FDD]/"*) core="np2kai_libretro";;
*"archive:ni-roms/roms/NEC - PC Engine - TurboGrafx-16.zip/"*) core="mednafen_pce_fast_libretro";;
*"archive:tosec-main/NEC/PC-Engine & TurboGrafx-16/Games/"*) core="mednafen_pce_fast_libretro";;
*"archive:mame-sl/mame-sl/pce.zip/"*) core="mame pce -cart";;
*"archive:mame-sl/mame-sl/tg16.zip/"*) core="mame tg16 -cart";;
*"FinalBurn Neo/tg16/"*) core="mednafen_pce_fast_libretro";;
*"archive:mame-sl/mame-sl/pce_tourvision.zip/"*) core="mame tourvis -cart";;
*"FinalBurn Neo/pce/"*) core="mednafen_pce_fast_libretro";;
*"archive:ni-roms/roms/NEC - PC Engine SuperGrafx.zip/"*) core="mednafen_supergrafx_libretro";;
*"archive:tosec-main/NEC/SuperGrafx/Games/"*) core="mednafen_supergrafx_libretro";;
*"archive:mame-sl/mame-sl/sgx.zip/"*) core="mame sgx -cart";;
*"FinalBurn Neo/sgx/"*) core="mednafen_supergrafx_libretro";;
*"archive:nec-pc-engine-cd-turbografx-cd-redump/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"archive:tosec-iso-nec/PC-Engine CD & TurboGrafx-16 CD/Games/[IMG]/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"archive:non-redump_nec-pc-engine-cd-turbografx-cd/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"archive:mame-software-list-chds-2/pcecd/"*) core="mame pce -cdrm";;
*"archive:nec-pc-fx-pc-fxga-redump/"*) core="mednafen_pcfx_libretro"; ext="cue";;
*"archive:tosec-iso-nec/PC-FX/Games/"*) core="mednafen_pcfx_libretro"; ext="cue";;
*"archive:ni-roms/roms/Fujitsu - FM-7 (Sector).zip/"*) core="mame fm7 -flop1";;
*"archive:tosec-main/Fujitsu/FM-7/Games/[D77]/"*) core="mame fm7 -flop1";;
*"archive:mame-sl/mame-sl/fm7_disk.zip/"*) core="mame fm7 -flop1";;
*"archive:mame-sl/mame-sl/fm7_cass.zip/"*) core="mame fm7 -autoboot_command 'RUN\"\"\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/fm8_cass.zip/"*) core="mame fm8 -autoboot_command 'RUN\"\"\n' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/fm77av.zip/"*) core="mame fm77av -flop1";;
*"archive:tosec-main/Fujitsu/FM77-AV/Games/[D77]/"*) core="mame fm77av -flop1";;
*"archive:noaen-redump-fujitsu-fm-towns/"*) core="mame fmtmarty -cdrm";;
*"archive:mame-sl/mame-sl/fmtowns_cd.zip/"*) core="mame fmtmarty -cdrm";;
*"archive:mame-software-list-chds-2/fmtowns_cd/"*) core="mame fmtmarty -cdrm";;
*"archive:mame-sl/mame-sl/fmtowns_flop_orig.zip/"*) core="mame fmtowns -flop1";;
*"archive:mame-sl/mame-sl/fmtowns_flop_misc.zip/"*) core="mame fmtowns -flop1";;
*"archive:tosec-main/Fujitsu/FM Towns/Games/[BIN]/"*) core="mame fmtmarty -cdrm";;
*"archive:tosec-main/Fujitsu/FM Towns/Games/[D77]/"*) core="mame fmtowns -flop1";;
*"archive:tosec-main/Fujitsu/FM Towns/Games/[D88]/"*) core="mame fmtowns -flop1";;
*"archive:tosec-main/Fujitsu/FM Towns/Games/[HDM]/"*) core="mame fmtowns -flop1";;
*"archive:tosec-main/Sharp/X1/Games/[2D]/"*) core="x1_libretro";;
*"archive:tosec-main/Sharp/X1/Games/[D88]/"*) core="x1_libretro";;
*"archive:mame-sl/mame-sl/x1_cass.zip/"*) core="mame x1 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/x1_flop.zip/"*) core="mame x1 -flop1";;
*"archive:tosec-main/Sharp/X68000/Games/[DIM]/"*) core="px68k_libretro";;
*"archive:tosec-main/Sharp/X68000/Applications/"*) core="px68k_libretro";;
*"archive:mame-sl/mame-sl/x68k_flop.zip/"*) core="mame x68000 -flop1";;
*"MAME/Software List ROMs (merged)/mz80k_cass/"*) core="mame mz80k -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sharp/MZ-700/Games/[MZF]/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sharp/MZ-700/Games/[MZT]/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mz700_cass.zip/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sharp/MZ-800 & MZ-1500/Games/[MZF]/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sharp/MZ-800 & MZ-1500/Games/[MZT]/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:mame-sl/mame-sl/mz800_cass.zip/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"archive:tosec-main/Sharp/MZ-2000 & MZ-2200/Games/[MZT]/"*) core="mame mz2000 -autoboot_command 'C' -autoboot_delay 5 -cass";;
*"archive:mame-sl/mame-sl/mz2000_cass.zip/"*) core="mame mz2000 -autoboot_command 'C' -autoboot_delay 5 -cass";;
*"MAME/Software List ROMs (merged)/mz2500_flop/"*) core="mame mz2500 -flop1";;
*"archive:ni-roms/roms/Casio - PV-1000.zip/"*) core="mame pv1000 -cart";;
*"archive:tosec-main/Casio/PV-1000/Games/"*) core="mame pv1000 -cart";;
*"archive:mame-sl/mame-sl/pv1000.zip/"*) core="mame pv1000 -cart";;
*"archive:tosec-main/Casio/PV-2000/Games/"*) core="mame pv2000 -cart";;
*"archive:mame-sl/mame-sl/pv2000.zip/"*) core="mame pv2000 -cart";;
*"archive:ni-roms/roms/Casio - Loopy (LittleEndian).zip/"*) core="mame casloopy -cart";;
*"archive:tosec-main/Casio/Loopy/Games/[BIN]/"*) core="mame casloopy -cart";;
*"archive:mame-sl/mame-sl/casloopy.zip/"*) core="mame casloopy -cart";;
*"archive:commodore-amiga-cdtv-redump/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CDTV/Games/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CDTV/Applications/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CDTV/Educational/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:tosec-iso-commodore/Amiga CDTV/Multimedia/[ISO]/"*) core="puae_libretro"; ext="cue";;
*"archive:mame-software-list-chds-2/cdtv/"*) core="mame cdtv -cdrm";;
*"archive:ef_Philips_cd-i_redump_2300/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:non-redump_philips-cdi/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:tosec-iso-philips/CD-i/Games/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:tosec-iso-philips/CD-i/Applications/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:tosec-iso-philips/CD-i/Educational/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:tosec-iso-philips/CD-i/Multimedia/"*) core="same_cdi_libretro"; ext="cue";;
*"archive:mame-software-list-chds-2/cdi/"*) core="mame cdimono1 -cdrm";;
*"archive:ef_panasonic_3do_redump_set_661/"*) core="opera_libretro"; ext="cue";;
*"archive:non-redump_panasonic_3do/"*) core="opera_libretro"; ext="cue";;
*"archive:tosec-iso-3do/3DO Interactive Multiplayer/Games/"*) core="opera_libretro"; ext="cue";;
*"archive:tosec-iso-3do/3DO Interactive Multiplayer/Applications/[ISO]/"*) core="opera_libretro"; ext="cue";;
*"archive:tosec-iso-3do/3DO Interactive Multiplayer/Educational/[ISO]/"*) core="opera_libretro"; ext="cue";;
*"archive:tosec-iso-3do/3DO Interactive Multiplayer/Multimedia/"*) core="opera_libretro"; ext="cue";;
*"Redump/Memorex - Visual Information System/"*) core="mame vis -cdrm"; ext="cue";;
*"archive:tosec-iso-memorex/Video Information System/Educational/"*) core="mame vis -cdrm"; ext="cue";;
*"archive:tosec-iso-memorex/Video Information System/Games/"*) core="mame vis -cdrm"; ext="cue";;
*"archive:tosec-iso-memorex/Video Information System/Multimedia/"*) core="mame vis -cdrm"; ext="cue";;
*"MAME/Software List CHDs (merged)/vis/"*) core="mame vis -cdrm";;
*"archive:mame-roms-merged_/MAME ROMs (merged)/"*) core="mame";;
*"archive:mame-0.264-roms-non-merged/"*) core="mame";;
*"archive:mame-0.260-roms-split_202310/"*) core="mame";;
*"archive:MAME0.37b5_MAME2000_Reference_Set_Update_2_ROMs_Samples/roms/"*) core="mame";;
*"archive:MAME2003_Reference_Set_MAME0.78_ROMs_CHDs_Samples/roms/"*) core="mame";;
*"MAME/Reference Sets/0.94 ROMs (non-merged)/"*) core="mame";;
*"archive:MAME0.106-Reference-Set-ROMs-CHDs-Samples/MAME0.106Non-Merged.zip/"*) core="mame";;
*"archive:MAME_2010_full_nonmerged_romsets/roms.zip/"*) core="mame";;
*"archive:MAME_2015_arcade_romsets/roms.zip/"*) core="mame";;
*"archive:MAME_2016_Arcade_Romsets/roms.zip/"*) core="mame";;
*"archive:mame-sl/mame-sl/vgmplay.zip/"*) core="mame vgmplay -quik";;
*"FinalBurn Neo/arcade/"*) core="fbneo_libretro";;
*"archive:mame-sl/mame-sl/neogeo.zip/"*) core="mame aes -cart";;
*"archive:snk-neo-geo-cd-redump/"*) core="neocd_libretro"; ext="cue";;
*"archive:tosec-iso-snk/Neo-Geo CD/Games/[ISO]/"*) core="neocd_libretro"; ext="cue";;
*"MAME/Software List CHDs (merged)/neocd/"*) core="mame neocdz -cdrm";;
*"archive:ni-roms/roms/SNK - NeoGeo Pocket.zip/"*) core="mednafen_ngp_libretro";;
*"archive:tosec-main/SNK/Neo-Geo Pocket/Games/"*) core="mednafen_ngp_libretro";;
*"archive:mame-sl/mame-sl/ngp.zip/"*) core="mame ngp -cart";;
*"FinalBurn Neo/ngp/"*) core="mednafen_ngp_libretro"; ext="bin";;
*"archive:ni-roms/roms/SNK - NeoGeo Pocket Color.zip/"*) core="mednafen_ngp_libretro";;
*"archive:tosec-main/SNK/Neo-Geo Pocket Color/Games/"*) core="mednafen_ngp_libretro";;
*"archive:mame-sl/mame-sl/ngpc.zip/"*) core="mame ngpc -cart";;
*"archive:ni-roms/roms/Epoch - Game Pocket Computer.zip/"*) core="mame gamepock -cart";;
*"archive:mame-sl/mame-sl/gamepock.zip/"*) core="mame gamepock -cart";;
*"archive:ni-roms/roms/Watara - Supervision.zip/"*) core="potator_libretro";;
*"archive:tosec-main/Watara/Supervision/Games/"*) core="potator_libretro";;
*"archive:mame-sl/mame-sl/svision.zip/"*) core="mame svision -cart";;
*"archive:ni-roms/roms/Bandai - WonderSwan.zip/"*) core="mednafen_wswan_libretro";;
*"archive:tosec-main/Bandai/WonderSwan/Games/"*) core="mednafen_wswan_libretro";;
*"archive:mame-sl/mame-sl/wswan.zip/"*) core="mame wswan -cart";;
*"archive:ni-roms/roms/Benesse - Pocket Challenge V2.zip/"*) core="mednafen_wswan_libretro";;
*"archive:ni-roms/roms/Bandai - WonderSwan Color.zip/"*) core="mednafen_wswan_libretro";;
*"archive:tosec-main/Bandai/WonderSwan Color/Games/"*) core="mednafen_wswan_libretro";;
*"archive:mame-sl/mame-sl/wscolor.zip/"*) core="mame wscolor -cart";;
*"archive:ni-roms/roms/Welback - Mega Duck.zip/"*) core="mame megaduck -cart";;
*"archive:mame-sl/mame-sl/megaduck.zip/"*) core="mame megaduck -cart";;
*"archive:mame-sl/mame-sl/microvision.zip/"*) core="mame microvsn -cart";;
*"archive:ni-roms/roms/Bit Corporation - Gamate.zip/"*) core="mame gamate -cart";;
*"archive:tosec-main/Bit Corporation/Gamate/Games/"*) core="mame gamate -cart";;
*"archive:mame-sl/mame-sl/gamate.zip/"*) core="mame gamate -cart";;
*"archive:mame-sl/mame-sl/juicebox.zip/"*) core="mame juicebox";;
*"archive:ni-roms/roms/Hartung - Game Master.zip/"*) core="mame gmaster -cart";;
*"archive:tosec-main/Hartung/Game Master/Games/"*) core="mame gmaster -cart";;
*"archive:mame-sl/mame-sl/gmaster.zip/"*) core="mame gmaster -cart";;
*"archive:ni-roms/roms/Tiger - Game.com.zip/"*) core="mame gamecom -cart1";;
*"archive:tosec-main/Tiger Electronics/Game.com/Games/"*) core="mame gamecom -cart1";;
*"archive:mame-sl/mame-sl/gamecom.zip/"*) core="mame gamecom -cart1";;
*"archive:ni-roms/roms/GamePark - GP32.zip/"*) core="mame gp32 -memc";;
*"archive:tosec-main/Game Park/GP32/Games/[SMC]/"*) core="mame gp32 -memc";;
*"archive:mame-sl/mame-sl/gp32.zip/"*) core="mame gp32 -memc";;
*"archive:ni-roms/roms/Entex - Adventure Vision.zip/"*) core="mame advision -cart";;
*"archive:tosec-main/Entex/Adventure Vision/Games/"*) core="mame advision -cart";;
*"archive:mame-sl/mame-sl/advision.zip/"*) core="mame advision -cart";;
*"archive:mame-sl/mame-sl/monon_color.zip/"*) core="mame mononcol -cart";;
*"archive:mame-sl/mame-sl/gameking.zip/"*) core="mame gameking -cart";;
*"archive:mame-sl/mame-sl/gameking3.zip/"*) core="mame gamekin3 -cart";;
*"archive:ni-roms/roms/Mobile - J2ME.zip/"*) core="freej2me_libretro"; ext="jar";;
*"archive:ni-roms/roms/Mobile - Palm OS (Digital).zip/"*) core="mu_libretro"; ext="prc";;
esac

if [ -n "$ext" ]; then
  umount -l ~/iso; mount-zip "$1" ~/iso
  rom=$(find ~/iso -type f -name "*.${ext}" | head -n 1)
else
  rom="$1"
fi

case "$1" in */ti99_cart/*|*/vic10/*|*/stv/*|*/myvision/*|*/ibm5150/*|*/ibm5170/*|*/ibmpcjr_cart/*|*/ibmpcjr_flop/*|*/cassvisn_cart/*|*/juicebox/*) rompath="$(dirname "$1");$HOME/share/bios"; rom="$(basename "${1%.*}")";; esac

if [[ "$core" == *"mame"* ]]; then
  core=$(echo "$core" | sed -E 's|(-hard[0-9]+) ([a-z0-9_]+):([a-z0-9_]+)|\1 '"$HOME"'/share/bios/\2/\3/\3.chd|g')
  filename="${rom##*/}"; basename="${filename%.*}"
  eval "cmd=($core)"
  "${cmd[@]}" "${rom}" ${rompath:+-rompath "$rompath"} -skip_gameinfo -snapname "${basename}"
  exit
fi

if [[ "$core" == *"libretro"* ]]; then
  retroarch -L ~/.config/retroarch/cores/${core}.so "${rom}"
else
  ${core} "${rom}"
fi

if [ -z "$core" ]; then
  ark "$1"
fi
