#!/bin/bash
head "$1"
adresar=$(dirname "$1")
adresar2="${adresar##*/}"
case "$adresar/" in
*"TIC-80/"*) core="tic80_libretro";;
*"LowresNX/"*) core="lowresnx_libretro";;
*"/wasm4/"*) core="wasm4_libretro";;
*"PICO-8/"*) core="pico8 -run";;
*"Voxatron/"*) core="vox";;
*"/arduboy/NoIntro/"*) core="arduous_libretro";;
*"/arduboy/TOSEC/"*) core="arduous_libretro";;
*"/uzebox/MAME/"*) core="mame uzebox -cart";;
*"/commanderx16/IMG/"*) core="x16emu"; ext="img";;
*"/commanderx16/PRG/"*) core="x16emu"; ext="prg";;
*"/vircon32/Vircon32/"*) core="vircon32_libretro";;
*"/chip8/MAME/"*) core="mame d6800 -quik";;
*"/atari2600/ROMS/"*) core="stella_libretro";;
*"/atari2600/NoIntro/"*) core="stella_libretro";;
*"/atari2600/TOSEC/"*) core="stella_libretro";;
*"/atari2600/Homebrew/"*) core="stella_libretro";;
*"/atari2600/Applications/"*) core="stella_libretro";;
*"/atari2600/Educational/"*) core="stella_libretro";;
*"/atari2600/MAME/"*) core="mame a2600 -cart";;
*"/atari2600/Cass MAME/"*) core="mame a2600 scharger -cass";;
*"/atari5200/NoIntro/"*) core="a5200_libretro";;
*"/atari5200/TOSEC/"*) core="a5200_libretro";;
*"/atari5200/Homebrew/"*) core="a5200_libretro";;
*"/atari5200/App/"*) core="a5200_libretro";;
*"/atari5200/MAME/"*) core="mame a5200 -cart";;
*"/atari7800/NoIntro/"*) core="prosystem_libretro";;
*"/atari7800/TOSEC/"*) core="prosystem_libretro";;
*"/atari7800/Homebrew/"*) core="prosystem_libretro";;
*"/atari7800/App/"*) core="prosystem_libretro";;
*"/atari7800/MAME/"*) core="mame a7800 -cart";;
*"/jaguar/NoIntro/"*) core="virtualjaguar_libretro";;
*"/jaguar/TOSEC/"*) core="virtualjaguar_libretro";;
*"/jaguar/MAME/"*) core="mame jaguar -cart";;
*"/jaguarcd/Redump/"*) core="bigpemu"; ext="cue";;
*"/jaguarcd/NonRedump/"*) core="bigpemu"; ext="cdi";;
*"/lynx/NoIntro/"*) core="mednafen_lynx_libretro";;
*"/lynx/TOSEC/"*) core="mednafen_lynx_libretro";;
*"/lynx/MAME/"*) core="mame lynx -cart"; ext="bin";;
*"/atari800/NoIntro/"*) core="atari800_libretro";;
*"/atari800/ATR/"*) core="atari800_libretro";;
*"/atari800/ATX/"*) core="atari800_libretro";;
*"/atari800/BIN/"*) core="atari800_libretro";;
*"/atari800/CAS/"*) core="atari800_libretro";;
*"/atari800/XEX/"*) core="atari800_libretro";;
*"/atari800/App ATR/"*) core="atari800_libretro";;
*"/atari800/App BIN/"*) core="atari800_libretro";;
*"/atari800/App CAS/"*) core="atari800_libretro";;
*"/atari800/App XEX/"*) core="atari800_libretro";;
*"/atari800/Edu ATR/"*) core="atari800_libretro";;
*"/atari800/Edu BIN/"*) core="atari800_libretro";;
*"/atari800/Edu CAS/"*) core="atari800_libretro";;
*"/atari800/Edu XEX/"*) core="atari800_libretro";;
*"/atari800/MAME/"*) core="mame a800 -cart1";;
*"/atari800/Flop MAME/"*) core="mame a800 -flop1";;
*"/xegs/MAME/"*) core="mame xegs -cart";;
*"/atarist/NoIntro/"*) core="hatari_libretro";;
*"/atarist/ST/"*) core="hatari_libretro";;
*"/atarist/STX/"*) core="hatari_libretro";;
*"/atarist/App ST/"*) core="hatari_libretro";;
*"/atarist/App STX/"*) core="hatari_libretro";;
*"/atarist/Edu ST/"*) core="hatari_libretro";;
*"/atarist/Edu STX/"*) core="hatari_libretro";;
*"/atarist/MAME/"*) core="mame st -flop";;
*"/apple1/TOSEC/"*) core="mame apple1 -cass";;
*"/apple1/App/"*) core="mame apple1 -cass";;
*"/apple1/MAME/"*) core="mame apple1 -cass";;
*"/apple2/DSK/"*) core="mame apple2ee -flop1";;
*"/apple2/WOZ/"*) core="mame apple2ee -flop1";;
*"/apple2/Edu DSK/"*) core="mame apple2ee -flop1";;
*"/apple2/Edu WOZ/"*) core="mame apple2ee -flop1";;
*"/apple2/App DSK/"*) core="mame apple2ee -flop1";;
*"/apple2/App WOZ/"*) core="mame apple2ee -flop1";;
*"/apple2/Cracked MAME/"*) core="mame apple2ee -flop1";;
*"/apple2/Misc MAME/"*) core="mame apple2ee -flop1";;
*"/apple2/Orig MAME/"*) core="mame apple2ee -flop1";;
*"/apple2/Cass MAME/"*) core="mame apple2ee -cass";;
*"/apple2gs/2MG/"*) core="mame apple2gs -flop3";;
*"/apple2gs/Edu/"*) core="mame apple2gs -flop3";;
*"/apple2gs/App/"*) core="mame apple2gs -flop3";;
*"/apple2gs/Cracked MAME/"*) core="mame apple2gs -flop3";;
*"/apple2gs/Misc MAME/"*) core="mame apple2gs -flop3";;
*"/apple2gs/Orig MAME/"*) core="mame apple2gs -flop3";;
*"/apple3/TOSEC/"*) core="mame apple3 -flop1";;
*"/apple3/App DSK/"*) core="mame apple3 -flop1";;
*"/apple3/App PO/"*) core="mame apple3 -flop1";;
*"/apple3/WAP PD/"*) core="mame apple3 -flop1";;
*"/apple3/MAME/"*) core="mame apple3 -flop1";;
*"/lisa/App IMAGE/"*) core="mame lisa -flop1";;
*"/lisa/App A2R/"*) core="mame lisa -flop1";;
*"/lisa/MAME/"*) core="mame lisa -flop1";;
*"/macintosh/Flop MAME/"*) core="mame macse -flop1";;
*"/macintosh/Orig MAME/"*) core="mame macse -flop1";;
*"/macintosh/Cracked MAME/"*) core="mame macse -flop1";;
*"/macintosh/HDflop MAME/"*) core="mame macse -flop1";;
*"/macintosh/HDD CHD/"*) core="mame macse -hard";;
*"/macintosh/TOSEC DSK/"*) core="mame macse -flop1";;
*"/macintosh/TOSEC IMG/"*) core="mame macse -flop1";;
*"/zx80/MAME/"*) core="mame zx80 -autoboot_command 'W\n' -autoboot_delay 3 -cass";;
*"/zx81/TOSEC/"*) core="81_libretro";;
*"/zx81/App/"*) core="81_libretro";;
*"/zx81/MAME/"*) core="mame zx81 -autoboot_command 'J\"\"\n' -autoboot_delay 3 -cass";;
*"/zxspectrum/DSK/"*) core="fuse_libretro";;
*"/zxspectrum/SCL/"*) core="fuse_libretro";;
*"/zxspectrum/TAP/"*) core="fuse_libretro";;
*"/zxspectrum/TRD/"*) core="fuse_libretro";;
*"/zxspectrum/TZX/"*) core="fuse_libretro";;
*"/zxspectrum/Z80/"*) core="fuse_libretro";;
*"/zxspectrum/Edu TAP/"*) core="fuse_libretro";;
*"/zxspectrum/Edu TZX/"*) core="fuse_libretro";;
*"/zxspectrum/Edu Z80/"*) core="fuse_libretro";;
*"/zxspectrum/App TAP/"*) core="fuse_libretro";;
*"/zxspectrum/App TZX/"*) core="fuse_libretro";;
*"/zxspectrum/App Z80/"*) core="fuse_libretro";;
*"/zxspectrum/MAME/"*) core="mame spectrum -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"/zxspectrum/Cass MAME/"*) core="mame tc2068 -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"/zxspectrum/Beta Disc MAME/"*) core="mame pentagon -flop";;
*"/zxspectrum/Opus Flop MAME/"*) core="mame spec128 -flop";;
*"/zxspectrum/Cart MAME/"*) core="mame specpls3 -cart";;
*"/zxspectrum/MGT Flop MAME/"*) core="mame spec128 -flop";;
*"/specpls3/MAME/"*) core="mame specpls3 -flop";;
*"/ql/Demos MDV/"*) core="mame ql -autoboot_command 'BOOT\n' -autoboot_delay 5 -utap1"; ext="mdv";;
*"/ql/Cass MAME/"*) core="mame ql -autoboot_command 'BOOT\n' -autoboot_delay 5 -utap1";;
*"/ql/Cart MAME/"*) core="mame ql -cart";;
*"/ql/Flop MAME/"*) core="mame ql -exp trump -flop";;
*"/z88/MAME/"*) core="mame z88 -cart1";;
*"/amstradcpc/DSK/"*) core="cap32_libretro";;
*"/amstradcpc/CDT/"*) core="cap32_libretro";;
*"/amstradcpc/SNA/"*) core="cap32_libretro";;
*"/amstradcpc/App/"*) core="cap32_libretro";;
*"/amstradcpc/Cass MAME/"*) core="mame cpc464 -autoboot_command 'RUN\"\n' -autoboot_delay 3 -cass";;
*"/amstradcpc/Flop MAME/"*) core="mame cpc6128 -flop1";;
*"/gx4000/TOSEC/"*) core="cap32_libretro";;
*"/gx4000/MAME/"*) core="mame gx4000 -cart";;
*"/pcw/MAME/"*) core="mame pcw8256 -flop";;
*"/pet/TOSEC/"*) core="vice_xpet_libretro";;
*"/pet/MAME/"*) core="mame pet2001n -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/pet/Flop MAME/"*) core="mame pet2001n -flop1";;
*"/pet/ROM MAME/"*) core="mame pet2001n -rom";;
*"/cplus4/NoIntro/"*) core="vice_xplus4_libretro";;
*"/cplus4/PRG/"*) core="vice_xplus4_libretro";;
*"/cplus4/TAP/"*) core="vice_xplus4_libretro";;
*"/cplus4/Utils/"*) core="vice_xplus4_libretro";;
*"/cplus4/MAME/"*) core="mame c16 -cart";;
*"/cplus4/Flop MAME/"*) core="mame c16 -flop";;
*"/cplus4/Cass MAME/"*) core="mame c16 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/vic10/MAME/"*) core="mame vic10";;
*"/c20/NoIntro/"*) core="vice_xvic_libretro";;
*"/c20/CRT/"*) core="vice_xvic_libretro";;
*"/c20/D64/"*) core="vice_xvic_libretro";;
*"/c20/PRG/"*) core="vice_xvic_libretro";;
*"/c20/TAP/"*) core="vice_xvic_libretro";;
*"/c20/App/"*) core="vice_xvic_libretro";;
*"/c20/MAME/"*) core="mame vic20 -cart";;
*"/cbm2/Cart MAME/"*) core="mame cbm610 -cart";;
*"/cbm2/Flop MAME/"*) core="mame cbm610 -autoboot_command 'DLOAD\"\"*\"\"\nRUN\n' -autoboot_delay 5 -flop1";;
*"/c64/NoIntro/"*) core="vice_x64sc_libretro";;
*"/c64/PP/"*) core="vice_x64sc_libretro";;
*"/c64/Tapes/"*) core="vice_x64sc_libretro";;
*"/c64/Adventure/"*) core="vice_x64sc_libretro";;
*"/c64/Arcade/"*) core="vice_x64sc_libretro";;
*"/c64/Boulder/"*) core="vice_x64sc_libretro";;
*"/c64/Cards/"*) core="vice_x64sc_libretro";;
*"/c64/Gambling/"*) core="vice_x64sc_libretro";;
*"/c64/Misc/"*) core="vice_x64sc_libretro";;
*"/c64/Racing/"*) core="vice_x64sc_libretro";;
*"/c64/Shootem/"*) core="vice_x64sc_libretro";;
*"/c64/Simulation/"*) core="vice_x64sc_libretro";;
*"/c64/Sports/"*) core="vice_x64sc_libretro";;
*"/c64/Strategy/"*) core="vice_x64sc_libretro";;
*"/c64/Edu D64/"*) core="vice_x64sc_libretro";;
*"/c64/Edu PRG/"*) core="vice_x64sc_libretro";;
*"/c64/Edu T64/"*) core="vice_x64sc_libretro";;
*"/c64/App D64/"*) core="vice_x64sc_libretro";;
*"/c64/App PRG/"*) core="vice_x64sc_libretro";;
*"/c64/App T64/"*) core="vice_x64sc_libretro";;
*"/c64/Cart MAME/"*) core="mame c64 -cart";;
*"/c64/Cass MAME/"*) core="mame c64 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/c64/Flop Orig MAME/"*) core="mame c64 -flop";;
*"/c64/Flop Misc MAME/"*) core="mame c64 -flop";;
*"/c128/D64/"*) core="vice_x128_libretro";;
*"/c128/PRG/"*) core="vice_x128_libretro";;
*"/c128/App/"*) core="vice_x128_libretro";;
*"/c128/Cart MAME/"*) core="mame c128 -cart";;
*"/c128/Flop MAME/"*) core="mame c128 -flop";;
*"/c128/Rom MAME/"*) core="mame c128 -rom";;
*"/amiga500/NoIntro/"*) core="puae_libretro";;
*"/amiga500/ADF/"*) core="puae_libretro";;
*"/amiga500/IPF/"*) core="puae_libretro";;
*"/amiga500/PD/"*) core="puae_libretro";;
*"/amiga500/SPS/"*) core="puae_libretro";;
*"/amiga500/Edu/"*) core="puae_libretro";;
*"/amiga500/App/"*) core="puae_libretro";;
*"/amiga500/App PD/"*) core="puae_libretro";;
*"/amiga500/Flop MAME/"*) core="mame a500 -flop";;
*"/amiga500/ECS Flop MAME/"*) core="mame a600 -flop";;
*"/amiga500/OCS Flop MAME/"*) core="mame a500 -flop";;
*"/amiga500/AGA Flop MAME/"*) core="mame a1200 -flop";;
*"/amiga1200/Redump/"*) core="puae_libretro"; ext="cue";;
*"/amiga1200/ISO/"*) core="puae_libretro"; ext="cue";;
*"/amiga1200/App/"*) core="puae_libretro"; ext="cue";;
*"/amiga1200/Multimedia/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/Redump/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/ISO/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/App/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/Edu/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/Multimedia/"*) core="puae_libretro"; ext="cue";;
*"/amigacd32/CHD/"*) core="mame cd32 -cdrm";;
*"/nes/NoIntro/"*) core="nestopia_libretro";;
*"/nes/TOSEC/"*) core="nestopia_libretro";;
*"/nes/MAME/"*) core="mame nes -cart";;
*"/nes/ADE MAME/"*) core="mame nes -cart";;
*"/nes/NTB MAME/"*) core="mame nes -cart1 nes:nantbb -cart2";;
*"/famicom/Cass MAME/"*) core="mame famicom famibs30 -cass";;
*"/fds/Disk System NoIntro/"*) core="nestopia_libretro";;
*"/fds/Disk System TOSEC/"*) core="nestopia_libretro";;
*"/fds/Disk System MAME/"*) core="mame fds -flop";;
*"/snes/NoIntro/"*) core="snes9x_libretro";;
*"/snes/TOSEC/"*) core="snes9x_libretro";;
*"/snes/MAME/"*) core="mame snes -cart";;
*"/snes/ST MAME/"*) core="mame snes -cart1 snes:sufami -cart2";;
*"/snes/BS-X MAME/"*) core="mame snes -cart";;
*"/snes-msu1/SNES MSU-1/"*) core="snes9x_libretro";;
*"/satellaview/NoIntro/"*) core="snes9x_libretro";;
*"/sufami/NoIntro/"*) core="snes9x_libretro";;
*"/sufami/TOSEC/"*) core="snes9x_libretro";;
*"/sgb/NoIntro/"*) core="mesen-s_libretro";;
*"/sgb/TOSEC/"*) core="mesen-s_libretro";;
*"/sgb/MAME/"*) core="mame supergb -cart";;
*"/n64/NoIntro/"*) core="mupen64plus_next_libretro";;
*"/n64/TOSEC/"*) core="mupen64plus_next_libretro";;
*"/n64/MAME/"*) core="mame n64 -cart";;
*"/n64dd/MAME/"*) core="mame n64dd -hard";;
*"/n64dd/TOSEC/"*) core="mame n64dd -hard";;
*"/gamecube/ISO/"*) core="dolphin_libretro"; ext="iso";;
*"/wii/Redump/"*) core="dolphin_libretro";;
*"/pokemini/NoIntro/"*) core="pokemini_libretro";;
*"/pokemini/TOSEC/"*) core="pokemini_libretro";;
*"/pokemini/MAME/"*) core="mame pokemini -cart";;
*"/virtualboy/NoIntro/"*) core="mednafen_vb_libretro";;
*"/virtualboy/TOSEC/"*) core="mednafen_vb_libretro";;
*"/virtualboy/MAME/"*) core="mame vboy -cart";;
*"/gb/NoIntro/"*) core="sameboy_libretro";;
*"/gb/TOSEC/"*) core="sameboy_libretro";;
*"/gb/MAME/"*) core="mame gameboy -cart";;
*"/gbc/NoIntro/"*) core="sameboy_libretro";;
*"/gbc/TOSEC/"*) core="sameboy_libretro";;
*"/gbc/MAME/"*) core="mame gbcolor -cart";;
*"/gba/NoIntro/"*) core="mgba_libretro";;
*"/gba/TOSEC/"*) core="mgba_libretro";;
*"/gba/MAME/"*) core="mame gba -cart";;
*"/gba/e-Reader MAME/"*) core="mame gba -cart";;
*"/nds/DS NoIntro/"*) core="melonds_libretro";;
*"/nds/DS Download/"*) core="melonds_libretro";;
*"/nds/DS TOSEC/"*) core="melonds_libretro";;
*"/dsi/NoIntro/"*) core="melondsds_libretro";;
*"/dsi/TOSEC/"*) core="melondsds_libretro";;
*"/3ds/NoIntro/"*) core="citra_libretro"; ext="3ds";;
*"/wiiu/Redump/"*) core="cemu -g";;
*"/svmu/TOSEC/"*) core="mame svmu -quik";;
*"/svmu/MAME/"*) core="mame svmu -quik";;
*"/sg1000/NoIntro/"*) core="gearsystem_libretro";;
*"/sg1000/TOSEC/"*) core="gearsystem_libretro";;
*"/sg1000/MAME/"*) core="mame sg1000 -cart";;
*"/sc3000/App/"*) core="mame sc3000 -cart";;
*"/sc3000/Edu/"*) core="mame sc3000 -cart";;
*"/sc3000/WAV/"*) core="mame sc3000 -autoboot_command 'LOAD\n' -autoboot_delay 5 -cass";;
*"/sc3000/Cart MAME/"*) core="mame sc3000 -cart";;
*"/sc3000/Cass MAME/"*) core="mame sc3000 -autoboot_command 'LOAD\n' -autoboot_delay 5 -cass";;
*"/sc3000/Flop MAME/"*) core="mame sf7000 -flop";;
*"/segaai/MAME/"*) core="mame segaai -card";;
*"/mastersystem/NoIntro/"*) core="gearsystem_libretro";;
*"/mastersystem/TOSEC/"*) core="gearsystem_libretro";;
*"/mastersystem/MAME/"*) core="mame sms -cart";;
*"/megadrive/NoIntro/"*) core="genesis_plus_gx_libretro";;
*"/megadrive/TOSEC/"*) core="genesis_plus_gx_libretro";;
*"/megadrive/MAME/"*) core="mame megadriv -cart";;
*"/megadrive/Mega-Tech MAME/"*) core="mame megatech -cart";;
*"/megadrive-msu/Sega MSU-MD/"*) core="genesis_plus_gx_libretro"; ext="md";;
*"/pico/NoIntro/"*) core="picodrive_libretro";;
*"/pico/TOSEC/"*) core="picodrive_libretro";;
*"/pico/MAME/"*) core="mame pico -cart";;
*"/beena/NoIntro/"*) core="mame beena -cart";;
*"/beena/TOSEC/"*) core="mame beena -cart";;
*"/beena/MAME/"*) core="mame beena -cart";;
*"/sega32x/NoIntro/"*) core="picodrive_libretro";;
*"/sega32x/TOSEC/"*) core="picodrive_libretro";;
*"/sega32x/MAME/"*) core="mame 32x -cart";;
*"/megacd/Redump/"*) core="picodrive_libretro"; ext="cue";;
*"/megacd/ISO/"*) core="picodrive_libretro"; ext="cue";;
*"/megacd/NonRedump/"*) core="picodrive_libretro"; ext="cue";;
*"/saturn/Redump/"*) core="yabasanshiro_libretro"; ext="cue";;
*"/saturn/NonRedump/"*) core="yabasanshiro_libretro"; ext="cue";;
*"/saturn/ISO/"*) core="yabasanshiro_libretro"; ext="cue";;
*"/stv/MAME/"*) core="mame stvbios";;
*"/dreamcast/Redump/"*) core="flycast_libretro"; ext="cue";;
*"/dreamcast/NonRedump/"*) core="flycast_libretro"; ext="gdi";;
*"/dreamcast/US/"*) core="flycast_libretro"; ext="gdi";;
*"/dreamcast/PAL/"*) core="flycast_libretro"; ext="gdi";;
*"/dreamcast/JP/"*) core="flycast_libretro"; ext="gdi";;
*"/model2/Sega Model 2/"*) core="mame";;
*"/model3/Sega Model 3/"*) core="mame";;
*"/gamegear/NoIntro/"*) core="gearsystem_libretro";;
*"/gamegear/TOSEC/"*) core="gearsystem_libretro";;
*"/gamegear/MAME/"*) core="mame gamegear -cart";;
*"/pockstat/TOSEC/"*) core="mame pockstat -cart";;
*"/smc777/MAME/"*) core="mame smc777 -flop1";;
*"/psx/CHD EUR/"*) core="pcsx_rearmed_libretro";;
*"/psx/CHD JAP/"*) core="pcsx_rearmed_libretro";;
*"/psx/CHD USA/"*) core="pcsx_rearmed_libretro";;
*"/psx/NonRedump/"*) core="pcsx_rearmed_libretro"; ext="cue";;
*"/ps2/CHD 1/"*) core="pcsx2";;
*"/ps2/CHD 2/"*) core="pcsx2";;
*"/ps2/CHD 3/"*) core="pcsx2";;
*"/ps2/NonRedump A-G/"*) core="pcsx2"; ext="iso";;
*"/ps2/NonRedump H-Q/"*) core="pcsx2"; ext="iso";;
*"/ps2/NonRedump R-Z/"*) core="pcsx2"; ext="iso";;
*"/psp/Redump/"*) core="ppsspp_libretro"; ext="iso";;
*"/psp/NonRedump/"*) core="ppsspp_libretro"; ext="iso";;
*"/psp/TOSEC/"*) core="ppsspp_libretro"; ext="iso";;
*"/dos/eXoDOS/"*) core="dosbox_pure_libretro";;
*"/dos/TOSEC/"*) core="dosbox_pure_libretro";;
*"/dos/App TOSEC/"*) core="dosbox_pure_libretro";;
*"/dos/Edu TOSEC/"*) core="dosbox_pure_libretro";;
*"/dos/TOSEC-ISO/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1982/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1983/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1985/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1988/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1990/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1991/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1996/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1997/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 1999/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 199x/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2002/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2003/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2008/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2009/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2011/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2014/"*) core="dosbox_pure_libretro";;
*"/dos/TDC 2015/"*) core="dosbox_pure_libretro";;
*"/ibm5150/MAME/"*) core="mame ibm5150 -hard1 ibm5150_hdd:freedos13_8086";;
*"/ibm5170/MAME/"*) core="mame ibm5170 -hard1 ibm5170_hdd:freedos13";;
*"/ibm5170/CDROM CHD/"*) core="mame ibm5170 -cdrom";;
*"/ibm5170/CDROM MAME/"*) core="mame ibm5170 -cdrom";;
*"/ibm5170/HDD CHD/"*) core="mame ibm5170 -hard";;
*"/ibmpcjr/Cart MAME/"*) core="mame ibmpcjr";;
*"/ibmpcjr/Flop MAME/"*) core="mame ibmpcjr -hard1 ibm5150_hdd:freedos13_8086";;
*"/msx1/NoIntro/"*) core="bluemsx_libretro";;
*"/msx1/TOSEC CAS/"*) core="bluemsx_libretro";;
*"/msx1/TOSEC DSK/"*) core="bluemsx_libretro";;
*"/msx1/TOSEC ROM/"*) core="bluemsx_libretro";;
*"/msx1/Cart MAME/"*) core="mame expert11 -cart1";;
*"/msx1/Cass MAME/"*) core="mame expert11 -autoboot_command 'RUN\"CAS:\"\n' -autoboot_delay 3 -cass";;
*"/msx1/Flop MAME/"*) core="mame svi738 -flop";;
*"/msx2/NoIntro/"*) core="bluemsx_libretro";;
*"/msx2/TOSEC DSK/"*) core="bluemsx_libretro";;
*"/msx2/TOSEC ROM/"*) core="bluemsx_libretro";;
*"/msx2/Cart MAME/"*) core="mame hbf1xd -cart1";;
*"/msx2/Flop MAME/"*) core="mame hbf1xd -flop";;
*"/msx2/Cass MAME/"*) core="mame hbf1xd -autoboot_command 'RUN\"CAS:\"\n' -autoboot_delay 3 -cass";;
*"/msx2+/TOSEC/"*) core="bluemsx_libretro";;
*"/msx2+/Cart MAME/"*) core="mame fsa1wsx -cart1";;
*"/msx2+/Flop MAME/"*) core="mame fsa1wsx -flop";;
*"/msxturbor/MSX TurboR/"*) core="bluemsx_libretro";;
*"/msxturbor/Flop MAME/"*) core="mame fsa1gt -flop1";;
*"/msxturbor/Cart MAME/"*) core="mame fsa1gt -cart1";;
*"/studio2/MAME/"*) core="mame studio2 -cart";;
*"/channelf/NoIntro/"*) core="freechaf_libretro";;
*"/channelf/TOSEC/"*) core="freechaf_libretro";;
*"/channelf/MAME/"*) core="mame channelf -cart";;
*"/vectrex/NoIntro/"*) core="vecx_libretro";;
*"/vectrex/TOSEC/"*) core="vecx_libretro";;
*"/vectrex/MAME/"*) core="mame vectrex -cart";;
*"/o2em/NoIntro/"*) core="o2em_libretro";;
*"/o2em/TOSEC/"*) core="o2em_libretro";;
*"/o2em/MAME/"*) core="mame videopac -cart";;
*"/videopacplus/NoIntro/"*) core="o2em_libretro";;
*"/videopacplus/TOSEC/"*) core="o2em_libretro";;
*"/intellivision/NoIntro/"*) core="freeintv_libretro";;
*"/intellivision/TOSEC/"*) core="freeintv_libretro";;
*"/intellivision/MAME/"*) core="mame intv -cart";;
*"/intellivision/ECS MAME/"*) core="mame intvecs -cart";;
*"/colecovision/NoIntro/"*) core="gearcoleco_libretro";;
*"/colecovision/TOSEC/"*) core="gearcoleco_libretro";;
*"/colecovision/MAME/"*) core="mame coleco -cart";;
*"/colecovision/Homebrew MAME/"*) core="mame coleco -cart";;
*"/scv/NoIntro/"*) core="emuscv_libretro";;
*"/scv/TOSEC/"*) core="emuscv_libretro";;
*"/scv/MAME/"*) core="mame scv -cart";;
*"/ctvboy/MAME/"*) core="mame ctvboy -cart";;
*"/sv8000/MAME/"*) core="mame sv8000 -cart";;
*"/astrocade/NoIntro/"*) core="mame astrocde -cart";;
*"/astrocade/TOSEC/"*) core="mame astrocde -cart";;
*"/astrocade/MAME/"*) core="mame astrocde -cart";;
*"/apfm1000/NoIntro/"*) core="mame apfm1000 -cart";;
*"/apfm1000/TOSEC/"*) core="mame apfm1000 -cart";;
*"/apfm1000/MAME/"*) core="mame apfm1000 -cart";;
*"/apfm1000/Cass MAME/"*) core="mame apfimag -cass";;
*"/crvision/NoIntro/"*) core="mame crvision -cart";;
*"/crvision/TOSEC/"*) core="mame crvision -cart";;
*"/crvision/MAME/"*) core="mame crvision -cart";;
*"/vsmile/NoIntro/"*) core="mame vsmile -cart";;
*"/vsmile/TOSEC/"*) core="mame vsmile -cart";;
*"/vsmile/MAME/"*) core="mame vsmile -cart";;
*"/vsmile/Cart MAME/"*) core="mame vsmilem -cart";;
*"/vsmileb/MAME/"*) core="mame vsmileb -cart";;
*"/arcadia/NoIntro/"*) core="mame arcadia -cart";;
*"/arcadia/TOSEC/"*) core="mame arcadia -cart";;
*"/arcadia/MAME/"*) core="mame arcadia -cart";;
*"/hyperscan/MAME/"*) core="mame hyprscan -cdrom";;
*"/supracan/NoIntro/"*) core="mame supracan -cart";;
*"/supracan/TOSEC/"*) core="mame supracan -cart";;
*"/supracan/MAME/"*) core="mame supracan -cart";;
*"/vc4000/NoIntro/"*) core="mame vc4000 -cart";;
*"/vc4000/MAME/"*) core="mame vc4000 -cart";;
*"/multivision/Othello Multivision/"*) core="gearsystem_libretro";;
*"/vii/MAME/"*) core="mame vii -cart";;
*"/unichamp/MAME/"*) core="mame unichamp -cart";;
*"/entexsag/MAME/"*) core="mame sag -cart";;
*"/ekara/MAME/"*) core="mame ekara -cart";;
*"/videoart/MAME/"*) core="mame videoart -cart";;
*"/pdp1/MAME/"*) core="mame pdp1 -ptap1";;
*"/sol20/MAME/"*) core="mame sol20 -cass1";;
*"/trs80/Model III/"*) core="mame trs80m3 -quik";;
*"/trs80/Model 4/"*) core="mame trs80m3 -quik";;
*"/trs80/MAME/"*) core="mame trs80m3 -quik";;
*"/trs80/Cass MAME/"*) core="mame trs80m3 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"/trs80/Flop MAME/"*) core="mame trs80m3 -flop1";;
*"/trs80/Model II MAME/"*) core="mame trs80m2 -flop1";;
*"/sorcerer/Cart MAME/"*) core="mame sorcerer -cart";;
*"/sorcerer/Cass MAME/"*) core="mame sorcerer -cart sorcerer_cart:basicpac -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 5 -cass1";;
*"/sorcerer/Flop MAME/"*) core="mame sorcererd -flop1";;
*"/z80ne/Cass MAME/"*) core="mame z80net -cass1";;
*"/z80ne/Flop MAME/"*) core="mame z80netf -flop1";;
*"/osborne1/MAME/"*) core="mame osborne1 -flop1";;
*"/jupace/MAME/"*) core="mame jupace -cass";;
*"/nascom/Snap MAME/"*) core="mame nascom2 -dump1";;
*"/nascom/Flop MAME/"*) core="mame nascom2 -flop1";;
*"/abc80/Flop MAME/"*) core="mame abc80 -flop1";;
*"/abc80/Cass MAME/"*) core="mame abc80 -cass";;
*"/abc80/ROM MAME/"*) core="mame abc80 -cart";;
*"/kaypro/MAME/"*) core="mame kaypro2x -flop1";;
*"/galaxy/MAME/"*) core="mame galaxy -autoboot_command 'OLD\nRUN\n' -autoboot_delay 3 -cass";;
*"/special/MAME/"*) core="mame special -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"/special/Flop MAME/"*) core="mame specimx -flop1";;
*"/apogee/MAME/"*) core="mame apogee -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"/radio86/MAME/"*) core="mame radio86 -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"/mikrosha/MAME/"*) core="mame mikrosha -autoboot_command 'I\n' -autoboot_delay 3 -cass";;
*"/partner/Cass MAME/"*) core="mame partner -cass";;
*"/partner/Flop MAME/"*) core="mame partner -flop1";;
*"/korvet/MAME/"*) core="mame korvet -flop1";;
*"/atom/TOSEC/"*) core="mame atom -flop1";;
*"/atom/MAME/"*) core="mame atom -flop1";;
*"/atom/ROM MAME/"*) core="mame atom -cart";;
*"/atom/Cass MAME/"*) core="mame atom -cass";;
*"/interact/MAME/"*) core="mame interact -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/spc1000/MAME/"*) core="mame spc1000 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/cgenie/TOSEC/"*) core="mame cgenie -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"/cgenie/Cass MAME/"*) core="mame cgenie -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"/dragon64/TOSEC/"*) core="mame dragon64 -autoboot_command 'CLOAD\n' -autoboot_delay 4 -cass";;
*"/dragon64/MAME/"*) core="mame dragon64 -autoboot_command 'CLOAD\n' -autoboot_delay 4 -cass";;
*"/dragon64/Flop MAME/"*) core="mame dragon64 -flop1";;
*"/dragon64/Cart MAME/"*) core="mame dragon64 -cart";;
*"/dragon64/OS-9 MAME/"*) core="mame dragon64 -flop1";;
*"/dragon64/Flex MAME/"*) core="mame dragon64 -flop1";;
*"/dragon64/Alpha Flop MAME/"*) core="mame dragon64 -flop1";;
*"/oricatmos/TAP/"*) core="mame orica -autoboot_command 'CLOAD\"\"\n' -autoboot_delay 4 -cass";;
*"/oricatmos/MAME/"*) core="mame orica -autoboot_command 'CLOAD\"\"\n' -autoboot_delay 4 -cass";;
*"/camplynx/MAME/"*) core="mame lynx48k -autoboot_command 'mload\"\"\n' -autoboot_delay 2 -cass";;
*"/camplynx/Flop MAME/"*) core="mame lynx128k -flop1";;
*"/orao/MAME/"*) core="mame orao -cass";;
*"/vg5k/MAME/"*) core="mame vg5k -cass";;
*"/pegasus/MAME/"*) core="mame pegasus -rom1";;
*"/juku/MAME/"*) core="mame juku -flop1";;
*"/x07/MAME/"*) core="mame x07 -cass";;
*"/alice/A32 MAME/"*) core="mame alice32 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/alice/A90 MAME/"*) core="mame alice90 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/mc10/TOSEC/"*) core="mame mc10 -cass";;
*"/mc10/MAME/"*) core="mame mc10 -cass";;
*"/phc25/MAME/"*) core="mame phc25 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/laser310/200/"*) core="mame laser310 -dump";;
*"/laser310/200 App/"*) core="mame laser310 -dump";;
*"/laser310/310 App/"*) core="mame laser310 -dump";;
*"/laser310/MAME/"*) core="mame laser310 -dump";;
*"/laser310/Cass MAME/"*) core="mame laser310 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 2 -cass";;
*"/bk/TOSEC/"*) core="bk_libretro";;
*"/bk/App/"*) core="bk_libretro";;
*"/bk/MAME/"*) core="mame bk0010 -cass";;
*"/pmd85/MAME/"*) core="mame pmd851 -autoboot_command 'MGLD 00\n' -autoboot_delay 3 -cass";;
*"/lviv/MAME/"*) core="mame lviv -autoboot_command 'CLOAD \"\"\nRUN\n' -autoboot_delay 3 -cass";;
*"/mc1000/MAME/"*) core="mame mc1000 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/pecom64/MAME/"*) core="mame pecom64 -autoboot_command 'PLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/spc1500/MAME/"*) core="mame spc1500 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/orion128/MAME/"*) core="mame orion128 -flop1";;
*"/orion128/Cass MAME/"*) core="mame orion128 -cass";;
*"/videobrain/MAME/"*) core="mame vidbrain -cart";;
*"/super80/Cass MAME/"*) core="mame super80 -cass";;
*"/super80/Flop MAME/"*) core="mame super80r -flop1";;
*"/bbcmicro/TOSEC/"*) core="mame bbcb -flop1";;
*"/bbcmicro/Flop MAME/"*) core="mame bbcb -flop1";;
*"/bbcmicro/Orig MAME/"*) core="mame bbcb -flop1";;
*"/bbcmicro/Micro Cass MAME/"*) core="mame bbcb -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"/bbcmicro/Micro ROM MAME/"*) core="mame bbcb -rom1";;
*"/bbcmicro/Master Cart MAME/"*) core="mame bbcm -cart";;
*"/bbcmicro/Master Flop MAME/"*) core="mame bbcm -flop1";;
*"/bbcmicro/Master Compact Flop MAME/"*) core="mame bbcmc -flop1";;
*"/ti99/MAME/"*) core="mame ti99_4a";;
*"/mbee/Cart MAME/"*) core="mame mbee -cart";;
*"/mbee/Quik MAME/"*) core="mame mbee -quik";;
*"/mbee/Flop MAME/"*) core="mame mbee56 -flop1";;
*"/m5/Cart MAME/"*) core="mame m5 -cart1";;
*"/m5/Cass MAME/"*) core="mame m5 -cart1 m5_cart:basici -autoboot_command 'CHAIN\n' -autoboot_delay 5 -cass";;
*"/aquarius/Cart MAME/"*) core="mame aquarius -cart1";;
*"/aquarius/Cass MAME/"*) core="mame aquarius -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/adam/TOSEC/"*) core="mame adam -flop1";;
*"/adam/App/"*) core="mame adam -flop1";;
*"/adam/MAME/"*) core="mame adam -flop1";;
*"/adam/Cass MAME/"*) core="mame adam -cass";;
*"/adam/Cart MAME/"*) core="mame adam -cart1";;
*"/spectravideo/Games/"*) core="bluemsx_libretro";;
*"/spectravideo/Various/"*) core="bluemsx_libretro";;
*"/spectravideo/MAME/"*) core="mame svi318 -autoboot_command 'CLOAD\nRUN\n' -autoboot_delay 3 -cass";;
*"/mtx/Cart MAME/"*) core="mame mtx512 -cart1";;
*"/mtx/Cass MAME/"*) core="mame mtx512 -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"/mtx/Flop MAME/"*) core="mame mtx512 -exp_ext sdxbas -flop1";;
*"/mtx/ROM MAME/"*) core="mame mtx512 -rom";;
*"/pencil2/MAME/"*) core="mame pencil2 -cart";;
*"/electron/TOSEC/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"/electron/App/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"/electron/Edu/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"/electron/MAME/"*) core="mame electron64 -autoboot_command '*T.\nCH.\"\"\n' -autoboot_delay 2 -cass";;
*"/electron/Flop MAME/"*) core="mame electron64 -flop";;
*"/electron/Cart MAME/"*) core="mame electron64 -exp plus1 -cart";;
*"/electron/ROM MAME/"*) core="mame electron64 -exp plus1 -rom";;
*"/tutor/TOSEC/"*) core="mame tutor -cart";;
*"/tutor/MAME/"*) core="mame tutor -cart";;
*"/exl100/MAME/"*) core="mame exl100 -cart";;
*"/compclr2/MAME/"*) core="mame compclr2 -flop1";;
*"/myvision/MAME/"*) core="mame myvision -cart";;
*"/einstein/MAME/"*) core="mame einstein -flop1";;
*"/kc85/Cass MAME/"*) core="mame kc85_4 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/kc85/Cart MAME/"*) core="mame kc85_4 -cart";;
*"/kc85/Flop MAME/"*) core="mame kc85_4 -flop1";;
*"/tvc/TC Computer CAS/"*) core="ep128emu_core_libretro";;
*"/tvc/TC Computer Flop MAME/"*) core="mame tvc64p -flop1";;
*"/tvc/TVC Cass MAME/"*) core="mame tvc64p -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/tvc/TVC Cart MAME/"*) core="mame tvc64p -cart";;
*"/rx78/NoIntro/"*) core="mame rx78 -cart";;
*"/rx78/TOSEC/"*) core="mame rx78 -cart";;
*"/rx78/Cart MAME/"*) core="mame rx78 -cart";;
*"/rx78/Cass MAME/"*) core="mame rx78 basic -cass";;
*"/coco/TOSEC/"*) core="mame coco3 -cart";;
*"/coco/App/"*) core="mame coco3 -cart";;
*"/coco/MAME/"*) core="mame coco3 -cart";;
*"/coco/Flop MAME/"*) core="mame coco3 -flop1";;
*"/samcoupe/DSK/"*) core="mame samcoupe -flop1";;
*"/samcoupe/MAME/"*) core="mame samcoupe -flop1";;
*"/samcoupe/Cass MAME/"*) core="mame samcoupe -autoboot_command 'LOAD \"\"\n' -autoboot_delay 3 -cass";;
*"/enterprise/64 & 128 BAS/"*) core="ep128emu_core_libretro";;
*"/enterprise/64 & 128 COM/"*) core="ep128emu_core_libretro";;
*"/enterprise/64 & 128 DTF/"*) core="ep128emu_core_libretro";;
*"/enterprise/64 & 128 Multipart/"*) core="ep128emu_core_libretro";;
*"/enterprise/64 & 128 Flop MAME/"*) core="mame ep128 -flop";;
*"/enterprise/Cart MAME/"*) core="mame ep128 -cart";;
*"/enterprise/Cass MAME/"*) core="mame ep128 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/vector06/MAME/"*) core="mame vector06 -flop1";;
*"/socrates/VTech Socrates/"*) core="mame socrates -cart";;
*"/thomson/MO5 K7/"*) core="theodore_libretro";;
*"/thomson/MO6 K7/"*) core="theodore_libretro";;
*"/thomson/TO7 K7/"*) core="theodore_libretro";;
*"/thomson/TO7 M7/"*) core="theodore_libretro";;
*"/thomson/TO8 FD/"*) core="theodore_libretro";;
*"/thomson/TO8 K7/"*) core="theodore_libretro";;
*"/thomson/TO8 SAP/"*) core="theodore_libretro";;
*"/thomson/MO5 Cart MAME/"*) core="mame mo5 -cart";;
*"/thomson/MO5 Cass MAME/"*) core="mame mo5 -autoboot_command 'RUN\"\"\n' -autoboot_delay 3 -cass";;
*"/thomson/MO5 Flop MAME/"*) core="mame mo5 -flop";;
*"/thomson/MO6 Cass MAME/"*) core="mame mo6 -autoboot_command '2\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"/thomson/MO6 Flop MAME/"*) core="mame mo6 -flop";;
*"/thomson/TO Flop MAME/"*) core="mame to8 -flop";;
*"/thomson/TO7 Cart MAME/"*) core="mame to7 -cart";;
*"/thomson/TO7 Cass MAME/"*) core="mame to7 -cart basic -autoboot_command '1\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"/thomson/TO8 Cass MAME/"*) core="mame to8 -autoboot_command '2\nRUN\"\"\n' -autoboot_delay 5 -cass";;
*"/thomson/MO5 QD MAME/"*) core="mame mo5 -flop";;
*"/thomson/TO7 QD MAME/"*) core="mame to7 -flop";;
*"/rainbow/MAME/"*) core="mame rainbow -flop1";;
*"/tiki100/MAME/"*) core="mame tiki100 -flop1";;
*"/pro128/Cass MAME/"*) core="mame pro128 -autoboot_command 'RUN\"CASS:\"\n' -autoboot_delay 8 -cass";;
*"/pro128/Cart MAME/"*) core="mame pro128 -cart";;
*"/pro128/Flop MAME/"*) core="mame pro128 -flop1";;
*"/pro128s/MAME/"*) core="mame pro128s -flop1";;
*"/archimedes/TOSEC/"*) core="mame aa4401 -flop";;
*"/archimedes/App/"*) core="mame aa4401 -flop";;
*"/archimedes/MAME/"*) core="mame aa4401 -flop";;
*"/pc60/MAME/"*) core="mame pc6001 -cart1";;
*"/pc80/PC-8001 N-BASIC Flop MAME/"*) core="mame pc8001mk2sr -flop1";;
*"/pc80/PC-8001mkII N80 Flop MAME/"*) core="mame pc8001mk2sr -flop1";;
*"/pc80/PC-8001mkIISR N80SR Flop MAME/"*) core="mame pc8001mk2sr -flop1";;
*"/pc88/TOSEC/"*) core="quasi88_libretro";;
*"/pc88/Flop MAME/"*) core="mame pc8801 -flop1";;
*"/pc88/Cass MAME/"*) core="mame pc8801 -cass";;
*"/pc98/TOSEC/"*) core="np2kai_libretro";;
*"/pc98/MAME/"*) core="mame pc9801 -flop1";;
*"/pc98/CHD/"*) core="mame pc9821 -cdrm";;
*"/pc98/CD MAME/"*) core="mame pc9821 -cdrm";;
*"/pc98/PC-9821 TOSEC/"*) core="np2kai_libretro";;
*"/pcengine/NoIntro/"*) core="mednafen_pce_fast_libretro";;
*"/pcengine/TOSEC/"*) core="mednafen_pce_fast_libretro";;
*"/pcengine/MAME/"*) core="mame pce -cart";;
*"/pcengine/TurboGrafx MAME/"*) core="mame tg16 -cart";;
*"/pcengine/PCE TourVision MAME/"*) core="mame tourvis -cart";;
*"/supergrafx/NoIntro/"*) core="mednafen_supergrafx_libretro";;
*"/supergrafx/TOSEC/"*) core="mednafen_supergrafx_libretro";;
*"/supergrafx/MAME/"*) core="mame sgx -cart";;
*"/pcenginecd/Redump/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"/pcenginecd/ISO/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"/pcenginecd/NonRedump/"*) core="mednafen_pce_fast_libretro"; ext="cue";;
*"/pcenginecd/CHD/"*) core="mame pce -cdrm";;
*"/pcfx/Redump/"*) core="mednafen_pcfx_libretro"; ext="cue";;
*"/pcfx/ISO/"*) core="mednafen_pcfx_libretro"; ext="cue";;
*"/fm7/NoIntro/"*) core="mame fm7 -flop1";;
*"/fm7/D77/"*) core="mame fm7 -flop1";;
*"/fm7/MAME/"*) core="mame fm7 -flop1";;
*"/fm7/FM-7 Cass MAME/"*) core="mame fm7 -autoboot_command 'RUN\"\"\n' -autoboot_delay 5 -cass";;
*"/fm7/FM-8 Cass MAME/"*) core="mame fm8 -autoboot_command 'RUN\"\"\n' -autoboot_delay 5 -cass";;
*"/fm7/FM-77AV Flop MAME/"*) core="mame fm77av -flop1";;
*"/fm7/FM-77AV TOSEC/"*) core="mame fm77av -flop1";;
*"/fmtowns/Redump/"*) core="mame fmtmarty -cdrm";;
*"/fmtowns/MAME/"*) core="mame fmtmarty -cdrm";;
*"/fmtowns/CHD/"*) core="mame fmtmarty -cdrm";;
*"/fmtowns/Flop Orig MAME/"*) core="mame fmtowns -flop1";;
*"/fmtowns/Flop Misc MAME/"*) core="mame fmtowns -flop1";;
*"/fmtowns/TOSEC BIN/"*) core="mame fmtmarty -cdrm";;
*"/fmtowns/TOSEC D77/"*) core="mame fmtowns -flop1";;
*"/fmtowns/TOSEC D88/"*) core="mame fmtowns -flop1";;
*"/fmtowns/TOSEC HDM/"*) core="mame fmtowns -flop1";;
*"/x1/2D/"*) core="x1_libretro";;
*"/x1/D88/"*) core="x1_libretro";;
*"/x1/Cass MAME/"*) core="mame x1 -autoboot_command 'LOAD\n' -autoboot_delay 3 -cass";;
*"/x1/Flop MAME/"*) core="mame x1 -flop1";;
*"/x68000/DIM/"*) core="px68k_libretro";;
*"/x68000/App/"*) core="px68k_libretro";;
*"/x68000/MAME/"*) core="mame x68000 -flop1";;
*"/mz700/MZF/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz700/MZT/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz700/MAME/"*) core="mame mz700 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz800/MZF/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz800/MZT/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz800/MAME/"*) core="mame mz800 -autoboot_command 'L\n' -autoboot_delay 3 -cass";;
*"/mz2000/MZT/"*) core="mame mz2000 -autoboot_command 'C' -autoboot_delay 5 -cass";;
*"/mz2000/MAME/"*) core="mame mz2000 -autoboot_command 'C' -autoboot_delay 5 -cass";;
*"/mz2500/MAME/"*) core="mame mz2500 -flop1";;
*"/pv1000/NoIntro/"*) core="mame pv1000 -cart";;
*"/pv1000/TOSEC/"*) core="mame pv1000 -cart";;
*"/pv1000/MAME/"*) core="mame pv1000 -cart";;
*"/pv2000/TOSEC/"*) core="mame pv2000 -cart";;
*"/pv2000/MAME/"*) core="mame pv2000 -cart";;
*"/loopy/NoIntro/"*) core="mame casloopy -cart";;
*"/loopy/TOSEC/"*) core="mame casloopy -cart";;
*"/loopy/MAME/"*) core="mame casloopy -cart";;
*"/amigacdtv/Redump/"*) core="puae_libretro"; ext="cue";;
*"/amigacdtv/ISO/"*) core="puae_libretro"; ext="cue";;
*"/amigacdtv/App/"*) core="puae_libretro"; ext="cue";;
*"/amigacdtv/Edu/"*) core="puae_libretro"; ext="cue";;
*"/amigacdtv/Multimedia/"*) core="puae_libretro"; ext="cue";;
*"/amigacdtv/CHD/"*) core="mame cdtv -cdrm";;
*"/cdi/Redump/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/NonRedump/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/TOSEC/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/App/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/Edu/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/Multimedia/"*) core="same_cdi_libretro"; ext="cue";;
*"/cdi/CHD/"*) core="mame cdimono1 -cdrm";;
*"/3do/Redump/"*) core="opera_libretro"; ext="cue";;
*"/3do/NonRedump/"*) core="opera_libretro"; ext="cue";;
*"/3do/TOSEC/"*) core="opera_libretro"; ext="cue";;
*"/3do/App/"*) core="opera_libretro"; ext="cue";;
*"/3do/Edu/"*) core="opera_libretro"; ext="cue";;
*"/3do/Multimedia/"*) core="opera_libretro"; ext="cue";;
*"/vis/Edu/"*) core="mame vis -cdrm"; ext="cue";;
*"/vis/Games/"*) core="mame vis -cdrm"; ext="cue";;
*"/vis/Multimedia/"*) core="mame vis -cdrm"; ext="cue";;
*"/mame/MAME/"*) core="mame";;
*"/mame/Non-Merged/"*) core="mame";;
*"/mame/Split/"*) core="mame";;
*"/mame/2000/"*) core="mame";;
*"/mame/2003/"*) core="mame";;
*"/mame/2006/"*) core="mame";;
*"/mame/2010/"*) core="mame";;
*"/mame/2015/"*) core="mame";;
*"/mame/2016/"*) core="mame";;
*"/vgmplay/MAME/"*) core="mame vgmplay -quik";;
*"/fbneo/FinalBurn Neo/"*) core="fbneo_libretro";;
*"/neogeo/MAME/"*) core="mame aes -cart";;
*"/neogeocd/Redump/"*) core="neocd_libretro"; ext="cue";;
*"/neogeocd/ISO/"*) core="neocd_libretro"; ext="cue";;
*"/ngp/NoIntro/"*) core="mednafen_ngp_libretro";;
*"/ngp/TOSEC/"*) core="mednafen_ngp_libretro";;
*"/ngp/MAME/"*) core="mame ngp -cart";;
*"/ngpc/NoIntro/"*) core="mednafen_ngp_libretro";;
*"/ngpc/TOSEC/"*) core="mednafen_ngp_libretro";;
*"/ngpc/MAME/"*) core="mame ngpc -cart";;
*"/gamepock/NoIntro/"*) core="mame gamepock -cart";;
*"/gamepock/MAME/"*) core="mame gamepock -cart";;
*"/supervision/NoIntro/"*) core="potator_libretro";;
*"/supervision/TOSEC/"*) core="potator_libretro";;
*"/supervision/MAME/"*) core="mame svision -cart";;
*"/wswan/NoIntro/"*) core="mednafen_wswan_libretro";;
*"/wswan/TOSEC/"*) core="mednafen_wswan_libretro";;
*"/wswan/MAME/"*) core="mame wswan -cart";;
*"/wswan/Pocket Challenge 2 NoIntro/"*) core="mednafen_wswan_libretro";;
*"/wswanc/NoIntro/"*) core="mednafen_wswan_libretro";;
*"/wswanc/TOSEC/"*) core="mednafen_wswan_libretro";;
*"/wswanc/MAME/"*) core="mame wscolor -cart";;
*"/megaduck/NoIntro/"*) core="mame megaduck -cart";;
*"/megaduck/MAME/"*) core="mame megaduck -cart";;
*"/microvision/MAME/"*) core="mame microvsn -cart";;
*"/gamate/NoIntro/"*) core="mame gamate -cart";;
*"/gamate/TOSEC/"*) core="mame gamate -cart";;
*"/gamate/MAME/"*) core="mame gamate -cart";;
*"/juicebox/MAME/"*) core="mame juicebox";;
*"/gmaster/NoIntro/"*) core="mame gmaster -cart";;
*"/gmaster/TOSEC/"*) core="mame gmaster -cart";;
*"/gmaster/MAME/"*) core="mame gmaster -cart";;
*"/gamecom/NoIntro/"*) core="mame gamecom -cart1";;
*"/gamecom/TOSEC/"*) core="mame gamecom -cart1";;
*"/gamecom/MAME/"*) core="mame gamecom -cart1";;
*"/gp32/NoIntro/"*) core="mame gp32 -memc";;
*"/gp32/TOSEC/"*) core="mame gp32 -memc";;
*"/gp32/MAME/"*) core="mame gp32 -memc";;
*"/advision/NoIntro/"*) core="mame advision -cart";;
*"/advision/TOSEC/"*) core="mame advision -cart";;
*"/advision/MAME/"*) core="mame advision -cart";;
*"/mononcolor/MAME/"*) core="mame mononcol -cart";;
*"/gameking/MAME/"*) core="mame gameking -cart";;
*"/gameking3/MAME/"*) core="mame gamekin3 -cart";;
*"/j2me/NoIntro/"*) core="freej2me_libretro"; ext="jar";;
*"/palm/NoIntro/"*) core="mu_libretro"; ext="prc";;
esac

if [ -n "$ext" ]; then
  umount -l ~/iso; mount-zip "$1" ~/iso
  rom=$(find ~/iso -type f -name "*.${ext}" | head -n 1)
else
  rom="$1"
fi

case "$1" in */ti99_cart/*|*/vic10/*|*/stv/*|*/myvision/*|*/ibm5150/*|*/ibm5170/*|*/ibmpcjr_cart/*|*/ibmpcjr_flop/*|*/cassvisn_cart/*|*/juicebox/*) rompath="$(dirname "$1");$HOME/share/bios"; rom="$(basename "${1%.*}")";; esac

if [[ "$core" == *"mame"* ]]; then
  core=$(echo "$core" | sed -E 's|(-hard[0-9]+) ([a-z0-9_]+):([a-z0-9_]+)|\1 '"$HOME"'/share/bios/\2/\3/\3.chd|g')
  filename="${rom##*/}"; basename="${filename%.*}"
  eval "cmd=($core)"
  "${cmd[@]}" "${rom}" ${rompath:+-rompath "$rompath"} -skip_gameinfo -snapname "${basename}"
  exit
fi

if [[ "$core" == *"libretro"* ]]; then
  retroarch -L ~/.config/retroarch/cores/${core}.so "${rom}"
else
  ${core} "${rom}"
fi

if [ -z "$core" ]; then
  ark "$1"
fi
