#!/bin/bash
head "$1"
adresar=$(dirname "$1")
adresar2="${adresar##*/}"
case "$adresar" in
*"TIC-80") core="tic80_libretro";;
*"WASM-4") core="wasm4_libretro";;
*"LowresNX") core="lowresnx_libretro";;
*"PICO-8") core="pico8 -run";;
*"Voxatron") core="vox";;
*"MAME/Software List ROMs (merged)/uzebox") core="mame uzebox -cart";;
*"MAME/Software List ROMs (split)/uzebox") core="mame uzebox -cart";;
*"Internet Archive/joyrider3774/all_vircon32_roms_and_media/all_vircon32_roms_and_media") core="vircon32_libretro";;
*"TOSEC/8-Bit Productions/Commander X16/Games/[IMG]") core="x16emu"; ext="img";;
*"TOSEC/8-Bit Productions/Commander X16/Games/[PRG]") core="x16emu"; ext="prg";;
*"MAME/Software List ROMs (merged)/pdp1_ptp") core="mame pdp1 -ptap1";;
*"MAME/Software List ROMs (merged)/vgmplay") core="mame vgmplay -quik";;
*"Miscellaneous/Atari Mania/Atari-2600-VCS-ROM-Collection/ROMS") core="stella_libretro";;
*"No-Intro/Atari - Atari 2600") core="stella_libretro";;
*"TOSEC/Atari/2600 & VCS/Games") core="stella_libretro";;
*"TOSEC/Atari/2600 & VCS/Homebrew/Games/[BIN]") core="stella_libretro";;
*"TOSEC/Atari/2600 & VCS/Applications") core="stella_libretro";;
*"TOSEC/Atari/2600 & VCS/Educational") core="stella_libretro";;
*"MAME/Software List ROMs (merged)/a2600") core="stella_libretro";;
*"MAME/Software List ROMs (split)/a2600") core="stella_libretro";;
*"No-Intro/Atari - Atari 5200") core="a5200_libretro";;
*"TOSEC/Atari/5200/Games") core="a5200_libretro";;
*"TOSEC/Atari/5200/Homebrew/Games") core="a5200_libretro";;
*"TOSEC/Atari/5200/Applications") core="a5200_libretro";;
*"MAME/Software List ROMs (merged)/a5200") core="a5200_libretro";;
*"MAME/Software List ROMs (split)/a5200") core="a5200_libretro";;
*"No-Intro/Atari - Atari 7800 (BIN)") core="prosystem_libretro";;
*"TOSEC/Atari/7800/Games") core="prosystem_libretro";;
*"TOSEC/Atari/7800/Homebrew/Games") core="prosystem_libretro";;
*"TOSEC/Atari/7800/Applications") core="prosystem_libretro";;
*"MAME/Software List ROMs (merged)/a7800") core="prosystem_libretro";;
*"MAME/Software List ROMs (split)/a7800") core="prosystem_libretro";;
*"No-Intro/Atari - Atari Jaguar (J64)") core="virtualjaguar_libretro";;
*"TOSEC/Atari/Jaguar/Games/[J64]") core="virtualjaguar_libretro";;
*"MAME/Software List ROMs (merged)/jaguar") core="virtualjaguar_libretro";;
*"MAME/Software List ROMs (split)/jaguar") core="virtualjaguar_libretro";;
*"Redump/Atari - Jaguar CD Interactive Multimedia System") core="bigpemu"; ext="cue";;
*"No-Intro/Non-Redump - Atari - Atari Jaguar CD") core="bigpemu"; ext="cdi";;
*"No-Intro/Atari - Atari Lynx (LYX)") core="mednafen_lynx_libretro";;
*"TOSEC/Atari/Lynx/Games/[LNX]") core="mednafen_lynx_libretro";;
*"MAME/Software List ROMs (merged)/lynx") core="mednafen_lynx_libretro"; ext="bin";;
*"MAME/Software List ROMs (split)/lynx") core="mednafen_lynx_libretro"; ext="bin";;
*"No-Intro/Atari - 8-bit Family") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Games/[ATR]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Games/[ATX]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Games/[BIN]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Games/[CAS]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Games/[XEX]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Applications/[ATR]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Applications/[BIN]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Applications/[CAS]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Applications/[XEX]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Educational/[ATR]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Educational/[BIN]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Educational/[CAS]") core="atari800_libretro";;
*"TOSEC/Atari/8bit/Educational/[XEX]") core="atari800_libretro";;
*"MAME/Software List ROMs (merged)/a800") core="atari800_libretro";;
*"MAME/Software List ROMs (split)/a800") core="atari800_libretro";;
*"MAME/Software List ROMs (merged)/xegs") core="mame xegs -cart";;
*"MAME/Software List ROMs (split)/xegs") core="mame xegs -cart";;
*"No-Intro/Atari - Atari ST") core="hatari_libretro";;
*"TOSEC/Atari/ST/Games/[ST]") core="hatari_libretro";;
*"TOSEC/Atari/ST/Games/[STX]") core="hatari_libretro";;
*"TOSEC/Atari/ST/Applications/[ST]") core="hatari_libretro";;
*"TOSEC/Atari/ST/Applications/[STX]") core="hatari_libretro";;
*"TOSEC/Atari/ST/Educational/[ST]") core="hatari_libretro";;
*"TOSEC/Atari/ST/Educational/[STX]") core="hatari_libretro";;
*"MAME/Software List ROMs (merged)/st_flop") core="hatari_libretro";;
*"MAME/Software List ROMs (split)/st_flop") core="hatari_libretro";;
*"TOSEC/Apple/II/Games/[DSK]") core="mame apple2ee -flop1";;
*"TOSEC/Apple/II/Games/[WOZ]") core="mame apple2ee -flop1";;
*"TOSEC/Apple/II/Educational/[DSK]") core="mame apple2ee -flop1";;
*"TOSEC/Apple/II/Educational/[WOZ]") core="mame apple2ee -flop1";;
*"TOSEC/Apple/II/Applications/[DSK]") core="mame apple2ee -flop1";;
*"TOSEC/Apple/II/Applications/[WOZ]") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (merged)/apple2_flop_clcracked") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (merged)/apple2_flop_misc") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (merged)/apple2_flop_orig") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (split)/apple2_flop_clcracked") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (split)/apple2_flop_misc") core="mame apple2ee -flop1";;
*"MAME/Software List ROMs (split)/apple2_flop_orig") core="mame apple2ee -flop1";;
*"TOSEC/Apple/IIGS/Games/[2MG]") core="mame apple2gs -flop3";;
*"TOSEC/Apple/IIGS/Educational/[2MG]") core="mame apple2gs -flop3";;
*"TOSEC/Apple/IIGS/Applications/[2MG]") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (merged)/apple2gs_flop_clcracked") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (merged)/apple2gs_flop_misc") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (merged)/apple2gs_flop_orig") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (split)/apple2gs_flop_clcracked") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (split)/apple2gs_flop_misc") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (split)/apple2gs_flop_orig") core="mame apple2gs -flop3";;
*"MAME/Software List ROMs (merged)/mac_flop") core="mame macse -flop1";;
*"MAME/Software List ROMs (merged)/mac_flop_orig") core="mame macse -flop1";;
*"MAME/Software List ROMs (merged)/mac_flop_clcracked") core="mame macse -flop1";;
*"MAME/Software List ROMs (merged)/mac_hdflop") core="mame macse -flop1";;
*"No-Intro/Fairchild - Channel F") core="freechaf_libretro";;
*"TOSEC/Fairchild/VES & Channel F/Games") core="freechaf_libretro";;
*"MAME/Software List ROMs (merged)/channelf") core="freechaf_libretro";;
*"MAME/Software List ROMs (split)/channelf") core="freechaf_libretro";;
*"No-Intro/GCE - Vectrex") core="vecx_libretro";;
*"TOSEC/GCE/Vectrex/Games") core="vecx_libretro";;
*"MAME/Software List ROMs (merged)/vectrex") core="vecx_libretro";;
*"MAME/Software List ROMs (split)/vectrex") core="vecx_libretro  ";;
*"No-Intro/Magnavox - Odyssey 2") core="o2em_libretro";;
*"TOSEC/Magnavox/Odyssey2/Games") core="o2em_libretro";;
*"MAME/Software List ROMs (merged)/videopac") core="o2em_libretro";;
*"MAME/Software List ROMs (split)/videopac") core="o2em_libretro";;
*"No-Intro/Philips - Videopac+") core="o2em_libretro";;
*"TOSEC/Philips/Videopac+/Games") core="o2em_libretro";;
*"No-Intro/Mattel - Intellivision") core="freeintv_libretro";;
*"TOSEC/Mattel/Intellivision/Games/[BIN]") core="freeintv_libretro";;
*"MAME/Software List ROMs (merged)/intv") core="freeintv_libretro";;
*"MAME/Software List ROMs (split)/intv") core="freeintv_libretro";;
*"No-Intro/Coleco - ColecoVision") core="bluemsx_libretro";;
*"TOSEC/Coleco/ColecoVision/Games") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/coleco") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/coleco") core="bluemsx_libretro";;
*"No-Intro/Epoch - Super Cassette Vision") core="emuscv_libretro";;
*"TOSEC/Epoch/Super Cassette Vision/Games") core="emuscv_libretro";;
*"MAME/Software List ROMs (merged)/scv") core="emuscv_libretro";;
*"MAME/Software List ROMs (split)/scv") core="emuscv_libretro";;
*"No-Intro/Epoch - Game Pocket Computer") core="mame gamepock -cart";;
*"No-Intro/Watara - Supervision") core="potator_libretro";;
*"TOSEC/Watara/Supervision/Games") core="potator_libretro";;
*"No-Intro/Bandai - WonderSwan") core="mednafen_wswan_libretro";;
*"TOSEC/Bandai/WonderSwan/Games") core="mednafen_wswan_libretro";;
*"No-Intro/Benesse - Pocket Challenge V2") core="mednafen_wswan_libretro";;
*"No-Intro/Bandai - WonderSwan Color") core="mednafen_wswan_libretro";;
*"TOSEC/Bandai/WonderSwan Color/Games") core="mednafen_wswan_libretro";;
*"No-Intro/Arduboy Inc - Arduboy") core="arduous_libretro";;
*"TOSEC/Arduboy/Arduboy/Games/[HEX]") core="arduous_libretro";;
*"No-Intro/Welback - Mega Duck") core="mame megaduck -cart";;
*"No-Intro/Bit Corporation - Gamate") core="mame gamate -cart";;
*"TOSEC/Bit Corporation/Gamate/Games") core="mame gamate -cart";;
*"No-Intro/Hartung - Game Master") core="mame gmaster -cart";;
*"TOSEC/Hartung/Game Master/Games") core="mame gmaster -cart";;
*"No-Intro/Tiger - Game.com") core="mame gamecom -cart1";;
*"TOSEC/Tiger Electronics/Game.com/Games") core="mame gamecom -cart1";;
*"No-Intro/GamePark - GP32") core="mame gp32 -memc";;
*"TOSEC/Game Park/GP32/Games/[SMC]") core="mame gp32 -memc";;
*"TOSEC/Amstrad/CPC/Games/[DSK]") core="cap32_libretro";;
*"TOSEC/Amstrad/CPC/Games/[CDT]") core="cap32_libretro";;
*"TOSEC/Amstrad/CPC/Games/[SNA]") core="cap32_libretro";;
*"TOSEC/Amstrad/CPC/Applications/[DSK]") core="cap32_libretro";;
*"MAME/Software List ROMs (merged)/cpc_flop") core="cap32_libretro";;
*"MAME/Software List ROMs (split)/cpc_flop") core="cap32_libretro";;
*"TOSEC/Amstrad/GX4000/Games") core="cap32_libretro";;
*"TOSEC/Sinclair/ZX81/Games/[P]") core="81_libretro";;
*"TOSEC/Sinclair/ZX81/Applications/[P]") core="81_libretro";;
*"MAME/Software List ROMs (merged)/zx81_cass") core="81_libretro";;
*"MAME/Software List ROMs (split)/zx81_cass") core="81_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[DSK]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[SCL]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[TAP]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[TRD]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[TZX]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Games/[Z80]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Educational/[TAP]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Educational/[TZX]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Educational/[Z80]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Applications/[TAP]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Applications/[TZX]") core="fuse_libretro";;
*"TOSEC/Sinclair/ZX Spectrum/Applications/[Z80]") core="fuse_libretro";;
*"MAME/Software List ROMs (merged)/spectrum_cass") core="fuse_libretro";;
*"MAME/Software List ROMs (split)/spectrum_cass") core="fuse_libretro";;
*"TOSEC/Spectravideo/SVI-318 & SVI-328/Games/[BIN]") core="bluemsx_libretro";;
*"TOSEC/Spectravideo/SVI-318 & SVI-328/Various/[CAS]") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/svi318_cass") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/svi318_cass") core="bluemsx_libretro";;
*"TOSEC/MGT/Sam Coupe/Games/[DSK]") core="mame samcoupe -flop1";;
*"MAME/Software List ROMs (merged)/samcoupe_flop") core="mame samcoupe -flop1";;
*"TOSEC/Tangerine/Oric-1 & Oric Atmos/Games/[TAP]") core="mame orica -cass";;
*"MAME/Software List ROMs (merged)/oric1_cass") core="mame orica -cass";;
*"MAME/Software List ROMs (split)/oric1_cass") core="mame orica -cass";;
*"MAME/Software List ROMs (merged)/camplynx_cass") core="mame lynx48k -cass";;
*"MAME/Software List ROMs (split)/camplynx_cass") core="mame lynx48k -cass";;
*"No-Intro/Bally - Astrocade") core="mame astrocde -cart";;
*"TOSEC/Bally/Professional Arcade & Astrocade/Games/[BIN]") core="mame astrocde -cart";;
*"No-Intro/APF - MP-1000") core="mame apfm1000 -cart";;
*"TOSEC/APF/M-1000/Games") core="mame apfm1000 -cart";;
*"No-Intro/Entex - Adventure Vision") core="mame advision -cart";;
*"TOSEC/Entex/Adventure Vision/Games") core="mame advision -cart";;
*"No-Intro/VTech - CreatiVision") core="mame crvision -cart";;
*"TOSEC/VTech/Laser 2001 & CreatiVision/Games") core="mame crvision -cart";;
*"No-Intro/VTech - V.Smile") core="mame vsmile -cart";;
*"TOSEC/VTech/V.Smile Motion/Games/[BIN]") core="mame vsmile -cart";;
*"No-Intro/Emerson - Arcadia 2001") core="mame arcadia -cart";;
*"TOSEC/Emerson/Arcadia 2001/Games") core="mame arcadia -cart";;
*"No-Intro/Casio - PV-1000") core="mame pv1000 -cart";;
*"TOSEC/Casio/PV-1000/Games") core="mame pv1000 -cart";;
*"No-Intro/Funtech - Super Acan") core="mame supracan -cart";;
*"TOSEC/Funtech/Super A'can/Games") core="mame supracan -cart";;
*"No-Intro/Interton - VC 4000") core="mame vc4000 -cart";;
*"TOSEC/Tsukuda Original/Othello Multivision/Games") core="gearsystem_libretro";;
*"TOSEC/Coleco/ColecoVision ADAM/Games/[DSK]") core="mame adam -flop1";;
*"TOSEC/Coleco/ColecoVision ADAM/Applications/[DSK]") core="mame adam -flop1";;
*"TOSEC/Tandy Radio Shack/TRS-80 Color Computer/Games/[ROM]") core="mame coco3 -cart";;
*"TOSEC/Tandy Radio Shack/TRS-80 Color Computer/Applications/[ROM]") core="mame coco3 -cart";;
*"Redump/Memorex - Visual Information System") core="mame vis -cdrm"; ext="cue";;
*"TOSEC-ISO/Memorex/Video Information System/Educational") core="mame vis -cdrm"; ext="cue";;
*"TOSEC-ISO/Memorex/Video Information System/Games") core="mame vis -cdrm"; ext="cue";;
*"TOSEC-ISO/Memorex/Video Information System/Multimedia") core="mame vis -cdrm"; ext="cue";;
*"TOSEC/Acorn/Atom/Games/[DSK]") core="mame atom -flop1";;
*"TOSEC/Acorn/BBC/Games/[SSD]") core="mame bbcb -flop1";;
*"TOSEC/Acorn/Electron/Games/[UEF]") core="mame electron64 -cass";;
*"TOSEC/Acorn/Electron/Applications/[UEF]") core="mame electron64 -cass";;
*"TOSEC/Acorn/Electron/Educational/[UEF]") core="mame electron64 -cass";;
*"TOSEC/Acorn/Archimedes/Games/[ADF]") core="mame aa4401 -flop";;
*"TOSEC/Acorn/Archimedes/Applications/[ADF]") core="mame aa4401 -flop";;
*"No-Intro/Fujitsu - FM-7 (Sector)") core="mame fm7 -flop1";;
*"TOSEC/Fujitsu/FM-7/Games/[D77]") core="mame fm7 -flop1";;
*"Redump/Fujitsu - FM-Towns") core="mame fmtmarty -cdrm";;
*"TOSEC/Tomy/Tutor & Pyuuta/Games") core="mame tutor -cart";;
*"TOSEC/VTech/Laser 200/Games/[VZ]") core="mame laser310 -dump";;
*"TOSEC/VTech/Laser 200/Applications") core="mame laser310 -dump";;
*"TOSEC/VTech/Laser 310/Applications") core="mame laser310 -dump";;
*"MAME/Software List ROMs (merged)/socrates") core="mame socrates -cart";;
*"MAME/Software List ROMs (merged)/ti99_cart") core="mame ti99_4a";;
*"TOSEC/Thomson/MO5/Games/[K7]") core="theodore_libretro";;
*"TOSEC/Thomson/MO6/Games") core="theodore_libretro";;
*"TOSEC/Thomson/TO7/Games/[K7]") core="theodore_libretro";;
*"TOSEC/Thomson/TO7/Games/[M7]") core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[FD]") core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[K7]") core="theodore_libretro";;
*"TOSEC/Thomson/TO8, TO8D, TO9, TO9+/Games/[SAP]") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/mo5_cart") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/mo5_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/mo5_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/mo6_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/mo6_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/to_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/to7_cart") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/to7_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (merged)/to8_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/mo5_cart") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/mo5_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/mo5_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/mo6_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/mo6_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/to_flop") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/to7_cart") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/to7_cass") core="theodore_libretro";;
*"MAME/Software List ROMs (split)/to8_cass") core="theodore_libretro";;
*"No-Intro/Nintendo - Nintendo Entertainment System (Headered)") core="nestopia_libretro";;
*"TOSEC/Nintendo/Famicom & Entertainment System/Games/[NES]") core="nestopia_libretro";;
*"MAME/Software List ROMs (merged)/nes") core="nestopia_libretro";;
*"MAME/Software List ROMs (split)/nes") core="nestopia_libretro";;
*"No-Intro/Nintendo - Family Computer Disk System (FDS)") core="nestopia_libretro";;
*"TOSEC/Nintendo/Famicom Disk System/Games/[FDS]") core="nestopia_libretro";;
*"No-Intro/Nintendo - Super Nintendo Entertainment System") core="snes9x_libretro";;
*"TOSEC/Nintendo/Super Famicom & Super Entertainment System/Games") core="snes9x_libretro";;
*"MAME/Software List ROMs (merged)/snes") core="snes9x_libretro";;
*"MAME/Software List ROMs (split)/snes") core="snes9x_libretro";;
*"T-En Collection/Nintendo - Super Famicom - MSU1") core="snes9x_libretro";;
*"T-En Collection/Nintendo - Super Famicom - MSU1 [roms only]") core="snes9x_libretro";;
*"No-Intro/Nintendo - Satellaview") core="snes9x_libretro";;
*"No-Intro/Nintendo - Sufami Turbo") core="snes9x_libretro";;
*"TOSEC/Nintendo/Sufami Turbo/Games") core="snes9x_libretro";;
*"No-Intro/Nintendo - Game Boy") core="mesen-s_libretro";;
*"TOSEC/Nintendo/Game Boy/Games") core="mesen-s_libretro";;
*"No-Intro/Nintendo - Nintendo 64 (ByteSwapped)") core="mupen64plus_next_libretro";;
*"TOSEC/Nintendo/64/Games") core="mupen64plus_next_libretro";;
*"MAME/Software List ROMs (merged)/n64") core="mupen64plus_next_libretro";;
*"MAME/Software List ROMs (split)/n64") core="mupen64plus_next_libretro";;
*"Redump/Nintendo - GameCube - NKit RVZ [zstd-19-128k]") core="dolphin_libretro"; ext="rvz";;
*"TOSEC-ISO/Nintendo/GameCube/Games") core="dolphin_libretro"; ext="iso";;
*"No-Intro/Unofficial - Nintendo - Wii (Digital) (Deprecated) (WAD)") core="dolphin_libretro"; ext="wad";;
*"Redump/Nintendo - Wii - NKit RVZ [zstd-19-128k]") core="dolphin_libretro"; ext="rvz";;
*"No-Intro/Nintendo - Pokemon Mini") core="pokemini_libretro";;
*"TOSEC/Nintendo/Pokemon Mini/Games") core="pokemini_libretro";;
*"No-Intro/Nintendo - Virtual Boy") core="mednafen_vb_libretro";;
*"TOSEC/Nintendo/Virtual Boy/Games") core="mednafen_vb_libretro";;
*"No-Intro/Nintendo - Game Boy") core="sameboy_libretro";;
*"TOSEC/Nintendo/Game Boy/Games") core="sameboy_libretro";;
*"MAME/Software List ROMs (merged)/gameboy") core="sameboy_libretro";;
*"MAME/Software List ROMs (split)/gameboy") core="sameboy_libretro";;
*"No-Intro/Nintendo - Game Boy Color") core="sameboy_libretro";;
*"TOSEC/Nintendo/Game Boy Color/Games/[GBC]") core="sameboy_libretro";;
*"MAME/Software List ROMs (merged)/gbcolor") core="sameboy_libretro";;
*"MAME/Software List ROMs (split)/gbcolor") core="sameboy_libretro";;
*"No-Intro/Nintendo - Game Boy Advance") core="mgba_libretro";;
*"TOSEC/Nintendo/Game Boy Advance/Games") core="mgba_libretro";;
*"MAME/Software List ROMs (merged)/gba") core="mgba_libretro";;
*"MAME/Software List ROMs (split)/gba") core="mgba_libretro";;
*"No-Intro/Nintendo - Nintendo DS (Decrypted)") core="melonds_libretro";;
*"No-Intro/Nintendo - Nintendo DS (Download Play)") core="melonds_libretro";;
*"TOSEC/Nintendo/DS/Games") core="melonds_libretro";;
*"No-Intro/Nintendo - Nintendo DSi (Decrypted)") core="melondsds_libretro";;
*"No-Intro/Nintendo - Nintendo 3DS (Decrypted)") core="citra_libretro"; ext="3ds";;
*"Redump/Nintendo - Wii U - WUX") core="cemu -g"; ext="wux";;
*"No-Intro/Sega - SG-1000 - SC-3000") core="gearsystem_libretro";;
*"TOSEC/Sega/Game 1000/Games") core="gearsystem_libretro";;
*"MAME/Software List ROMs (merged)/sg1000") core="gearsystem_libretro";;
*"MAME/Software List ROMs (split)/sg1000") core="gearsystem_libretro";;
*"No-Intro/Sega - Master System - Mark III") core="gearsystem_libretro";;
*"TOSEC/Sega/Mark III & Master System/Games") core="gearsystem_libretro";;
*"MAME/Software List ROMs (merged)/sms") core="gearsystem_libretro";;
*"MAME/Software List ROMs (split)/sms") core="gearsystem_libretro";;
*"No-Intro/Sega - Mega Drive - Genesis") core="genesis_plus_gx_libretro";;
*"TOSEC/Sega/Mega Drive & Genesis/Games/[BIN]") core="genesis_plus_gx_libretro";;
*"MAME/Software List ROMs (merged)/megadriv") core="genesis_plus_gx_libretro";;
*"MAME/Software List ROMs (split)/megadriv") core="genesis_plus_gx_libretro";;
*"T-En Collection/Sega - Mega Drive - MSU-MD") core="genesis_plus_gx_libretro"; ext="md";;
*"No-Intro/Sega - PICO") core="picodrive_libretro";;
*"TOSEC/Sega/Pico/Educational") core="picodrive_libretro";;
*"MAME/Software List ROMs (merged)/pico") core="picodrive_libretro";;
*"MAME/Software List ROMs (split)/pico") core="picodrive_libretro";;
*"No-Intro/Sega - 32X") core="picodrive_libretro";;
*"TOSEC/Sega/32X/Games") core="picodrive_libretro";;
*"MAME/Software List ROMs (merged)/32x") core="picodrive_libretro";;
*"MAME/Software List ROMs (split)/32x") core="picodrive_libretro";;
*"Redump/Sega - Mega CD & Sega CD") core="picodrive_libretro"; ext="cue";;
*"TOSEC-ISO/Sega/Mega-CD & Sega CD/CD/Games/[ISO]") core="picodrive_libretro"; ext="cue";;
*"Redump/Sega - Saturn") core="yabasanshiro_libretro"; ext="cue";;
*"No-Intro/Non-Redump - Sega - Sega Saturn") core="yabasanshiro_libretro"; ext="cue";;
*"TOSEC-ISO/Sega/Saturn/Games/[ISO]") core="yabasanshiro_libretro"; ext="cue";;
*"Redump/Sega - Dreamcast") core="flycast_libretro"; ext="cue";;
*"No-Intro/Non-Redump - Sega - Dreamcast") core="flycast_libretro"; ext="gdi";;
*"TOSEC-ISO/Sega/Dreamcast/Games/US") core="flycast_libretro"; ext="gdi";;
*"TOSEC-ISO/Sega/Dreamcast/Games/PAL") core="flycast_libretro"; ext="gdi";;
*"TOSEC-ISO/Sega/Dreamcast/Games/JP") core="flycast_libretro"; ext="gdi";;
*"No-Intro/Sega - Game Gear") core="gearsystem_libretro";;
*"TOSEC/Sega/Game Gear/Games") core="gearsystem_libretro";;
*"MAME/Software List ROMs (merged)/gamegear") core="gearsystem_libretro";;
*"MAME/Software List ROMs (split)/gamegear") core="gearsystem_libretro";;
*"Redump/Sony - PlayStation") core="pcsx_rearmed_libretro"; ext="cue";;
*"No-Intro/Non-Redump - Sony - PlayStation") core="pcsx_rearmed_libretro"; ext="cue";;
*"Redump/Sony - PlayStation 2") core="pcsx2"; ext="iso";;
*"No-Intro/Non-Redump - Sony - PlayStation 2") core="pcsx2"; ext="iso";;
*"Redump/Sony - PlayStation Portable") core="ppsspp_libretro"; ext="iso";;
*"No-Intro/Non-Redump - Sony - PlayStation Portable") core="ppsspp_libretro"; ext="iso";;
*"No-Intro/Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)") core="ppsspp_libretro"; ext="iso";;
*"TOSEC-ISO/Sony/PlayStation Portable/Games/[ISO]") core="ppsspp_libretro"; ext="iso";;
*"No-Intro/NEC - PC Engine - TurboGrafx-16") core="mednafen_pce_fast_libretro";;
*"TOSEC/NEC/PC-Engine & TurboGrafx-16/Games") core="mednafen_pce_fast_libretro";;
*"MAME/Software List ROMs (merged)/pce") core="mednafen_pce_fast_libretro";;
*"MAME/Software List ROMs (split)/pce") core="mednafen_pce_fast_libretro";;
*"MAME/Software List ROMs (merged)/tg16") core="mednafen_pce_fast_libretro";;
*"MAME/Software List ROMs (split)/tg16") core="mednafen_pce_fast_libretro";;
*"MAME/Software List ROMs (merged)/pce_tourvision") core="mednafen_pce_fast_libretro";;
*"Redump/NEC - PC Engine CD & TurboGrafx CD") core="mednafen_pce_fast_libretro"; ext="cue";;
*"TOSEC-ISO/NEC/PC-Engine CD & TurboGrafx-16 CD/Games/[IMG]") core="mednafen_pce_fast_libretro"; ext="cue";;
*"No-Intro/NEC - PC Engine SuperGrafx") core="mednafen_supergrafx_libretro";;
*"TOSEC/NEC/SuperGrafx/Games") core="mednafen_supergrafx_libretro";;
*"Redump/NEC - PC-FX & PC-FXGA") core="mednafen_pcfx_libretro"; ext="cue";;
*"TOSEC-ISO/NEC/PC-FX/Games") core="mednafen_pcfx_libretro"; ext="cue";;
*"Redump/Philips - CD-i") core="same_cdi_libretro"; ext="cue";;
*"No-Intro/Non-Redump - Philips - CD-i") core="same_cdi_libretro"; ext="cue";;
*"TOSEC-ISO/Philips/CD-i/Games") core="same_cdi_libretro"; ext="cue";;
*"TOSEC-ISO/Philips/CD-i/Applications") core="same_cdi_libretro"; ext="cue";;
*"TOSEC-ISO/Philips/CD-i/Educational") core="same_cdi_libretro"; ext="cue";;
*"TOSEC-ISO/Philips/CD-i/Multimedia") core="same_cdi_libretro"; ext="cue";;
*"Redump/Panasonic - 3DO Interactive Multiplayer") core="opera_libretro"; ext="cue";;
*"No-Intro/Non-Redump - Panasonic - 3DO Interactive Multiplayer") core="opera_libretro"; ext="cue";;
*"TOSEC-ISO/3DO/3DO Interactive Multiplayer/Games") core="opera_libretro"; ext="cue";;
*"TOSEC-ISO/3DO/3DO Interactive Multiplayer/Applications/[ISO]") core="opera_libretro"; ext="cue";;
*"TOSEC-ISO/3DO/3DO Interactive Multiplayer/Educational/[ISO]") core="opera_libretro"; ext="cue";;
*"TOSEC-ISO/3DO/3DO Interactive Multiplayer/Multimedia") core="opera_libretro"; ext="cue";;
*"eXo/eXoDOS/Full Release/eXo/eXoDOS") core="dosbox_pure_libretro";;
*"TOSEC/IBM/PC Compatibles/Games/[IMG]") core="dosbox_pure_libretro";;
*"TOSEC-ISO/IBM/PC Compatibles/CD/Games/[ISO]") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1981") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1982") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1983") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1984") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1985") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1986") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1987") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1988") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1989") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/198x") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1990") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1991") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1992") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1993") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1994") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1995") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1996") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1997") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1998") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/1999") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/199x") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/19xx") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2000") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2001") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2002") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2003") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2004") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2005") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2006") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2007") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2008") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2009") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2010") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2011") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2012") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2013") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2014") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2015") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2016") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2017") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2018") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2019") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2020") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2021") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2022") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2023") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2024") core="dosbox_pure_libretro";;
*"Total DOS Collection/Games/Files/2025") core="dosbox_pure_libretro";;
*"TOSEC/Commodore/PET/Games/[PRG]") core="vice_xpet_libretro";;
*"No-Intro/Commodore - Plus-4") core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Games/[PRG]") core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Games/[TAP]") core="vice_xplus4_libretro";;
*"TOSEC/Commodore/C16, C116 & Plus-4/Utilities/[PRG]") core="vice_xplus4_libretro";;
*"No-Intro/Commodore - VIC-20") core="vice_xvic_libretro";;
*"TOSEC/Commodore/VIC20/Games/[CRT]/Singlepart") core="vice_xvic_libretro";;
*"TOSEC/Commodore/VIC20/Games/[D64]") core="vice_xvic_libretro";;
*"TOSEC/Commodore/VIC20/Games/[PRG]/Singlepart") core="vice_xvic_libretro";;
*"TOSEC/Commodore/VIC20/Games/[TAP]") core="vice_xvic_libretro";;
*"TOSEC/Commodore/VIC20/Applications/[PRG]/Singlepart") core="vice_xvic_libretro";;
*"No-Intro/Commodore - Commodore 64") core="vice_x64sc_libretro";;
*"No-Intro/Commodore - Commodore 64 (PP)") core="vice_x64sc_libretro";;
*"No-Intro/Commodore - Commodore 64 (Tapes)") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Adventure/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Arcade/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Boulder Dash/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Cards/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Gambling/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Misc/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Racing/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Shoot'em Up/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Simulation/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Sports/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Games/Strategy/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Educational/[D64]") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C64/Applications/[D64]") core="vice_x64sc_libretro";;
*"MAME/Software List ROMs (merged)/c64_cass") core="vice_x64sc_libretro";;
*"MAME/Software List ROMs (split)/c64_cass") core="vice_x64sc_libretro";;
*"TOSEC/Commodore/C128/Games/[D64]") core="vice_x128_libretro";;
*"TOSEC/Commodore/C128/Games/[PRG]") core="vice_x128_libretro";;
*"TOSEC/Commodore/C128/Applications/[D64]") core="vice_x128_libretro";;
*"No-Intro/Commodore - Amiga") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Games/[ADF]") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Games/[Unofficial IPF]") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Games/Public Domain/[ADF]") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Games/SPS") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Educational/[ADF]") core="puae_libretro";;
*"TOSEC/Commodore/Amiga/Applications/[ADF]") core="puae_libretro";;
*"MAME/Software List ROMs (merged)/amiga_flop") core="puae_libretro";;
*"MAME/Software List ROMs (split)/amiga_flop") core="puae_libretro";;
*"MAME/Software List ROMs (merged)/amigaecs_flop") core="puae_libretro";;
*"MAME/Software List ROMs (split)/amigaecs_flop") core="puae_libretro";;
*"MAME/Software List ROMs (merged)/amigaocs_flop") core="puae_libretro";;
*"MAME/Software List ROMs (split)/amigaocs_flop") core="puae_libretro";;
*"MAME/Software List ROMs (merged)/amigaaga_flop") core="puae_libretro";;
*"MAME/Software List ROMs (split)/amigaaga_flop") core="puae_libretro";;
*"Redump/Commodore - Amiga CD") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga/CD/Games/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga/CD/Applications/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga/CD/Multimedia/[ISO]") core="puae_libretro"; ext="cue";;
*"Redump/Commodore - Amiga CDTV") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CDTV/Games/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CDTV/Applications/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CDTV/Educational/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CDTV/Multimedia/[ISO]") core="puae_libretro"; ext="cue";;
*"Redump/Commodore - Amiga CD32") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CD32/Games/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CD32/Applications") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CD32/Educational/[ISO]") core="puae_libretro"; ext="cue";;
*"TOSEC-ISO/Commodore/Amiga CD32/Multimedia/[ISO]") core="puae_libretro"; ext="cue";;
*"No-Intro/Microsoft - MSX") core="bluemsx_libretro";;
*"TOSEC/MSX/MSX/Games/[DSK]") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx1_cart") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx1_cart") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx1_cass") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx1_cass") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx1_flop") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx1_flop") core="bluemsx_libretro";;
*"No-Intro/Microsoft - MSX2") core="bluemsx_libretro";;
*"TOSEC/MSX/MSX2/Games/[DSK]") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx2_cart") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx2_cart") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx2_flop") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx2_flop") core="bluemsx_libretro";;
*"TOSEC/MSX/MSX2+/Games") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msx2p_flop") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msx2p_flop") core="bluemsx_libretro";;
*"TOSEC/MSX/TurboR/Games") core="bluemsx_libretro";;
*"MAME/Software List ROMs (merged)/msxr_flop") core="bluemsx_libretro";;
*"MAME/Software List ROMs (split)/msxr_flop") core="bluemsx_libretro";;
*"TOSEC/NEC/PC-8801/Games/[D88]") core="quasi88_libretro";;
*"MAME/Software List ROMs (merged)/pc8801_flop") core="quasi88_libretro";;
*"MAME/Software List ROMs (split)/pc8801_flop") core="quasi88_libretro";;
*"TOSEC/NEC/PC-9801/Games/[FDD]") core="np2kai_libretro";;
*"MAME/Software List ROMs (merged)/pc98") core="np2kai_libretro";;
*"MAME/Software List ROMs (split)/pc98") core="np2kai_libretro";;
*"TOSEC/Sharp/X1/Games/[2D]") core="x1_libretro";;
*"TOSEC/Sharp/X1/Games/[D88]") core="x1_libretro";;
*"MAME/Software List ROMs (merged)/x1_cass") core="x1_libretro";;
*"MAME/Software List ROMs (split)/x1_cass") core="x1_libretro";;
*"MAME/Software List ROMs (merged)/x1_flop") core="x1_libretro";;
*"MAME/Software List ROMs (split)/x1_flop") core="x1_libretro";;
*"TOSEC/Sharp/X68000/Games/[DIM]") core="px68k_libretro";;
*"TOSEC/Sharp/X68000/Applications") core="px68k_libretro";;
*"MAME/Software List ROMs (merged)/x68k_flop") core="px68k_libretro";;
*"MAME/Software List ROMs (split)/x68k_flop") core="px68k_libretro";;
*"MAME/ROMs (merged)") core="mame";;
*"MAME/ROMs (non-merged)") core="mame";;
*"MAME/ROMs (split)") core="mame";;
*"MAME/Reference Sets/0.37b5 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.78 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.94 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.106 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.139 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.160 ROMs (non-merged)") core="mame";;
*"MAME/Reference Sets/0.174 ROMs (non-merged)") core="mame";;
*"FinalBurn Neo/arcade") core="fbneo_libretro";;
*"Internet Archive/chadmaster/m2emu1.1a/Sega Model 2 Emu 1.1a and Full Romset/Model 2 Romset (Merged)") core="mame";;
*"Internet Archive/chadmaster/segamodel3/ROMs") core="mame";;
*"MAME/Software List ROMs (merged)/neogeo") core="fbneo_libretro";;
*"MAME/Software List ROMs (split)/neogeo") core="fbneo_libretro";;
*"Redump/SNK - Neo Geo CD") core="neocd_libretro"; ext="cue";;
*"TOSEC-ISO/SNK/Neo-Geo CD/Games/[ISO]") core="neocd_libretro"; ext="cue";;
*"No-Intro/SNK - NeoGeo Pocket") core="mednafen_ngp_libretro";;
*"TOSEC/SNK/Neo-Geo Pocket/Games") core="mednafen_ngp_libretro";;
*"MAME/Software List ROMs (merged)/ngp") core="mednafen_ngp_libretro"; ext="bin";;
*"No-Intro/SNK - NeoGeo Pocket Color") core="mednafen_ngp_libretro";;
*"TOSEC/SNK/Neo-Geo Pocket Color/Games") core="mednafen_ngp_libretro";;
*"MAME/Software List ROMs (merged)/ngpc") core="mednafen_ngp_libretro"; ext="bin";;
*"MAME/Software List ROMs (split)/ngpc") core="mednafen_ngp_libretro"; ext="bin";;
esac

if [ -n "$ext" ]; then
  umount -l ~/iso; mount-zip "$1" ~/iso
  rom=$(find ~/iso -type f -name "*.${ext}" | head -n 1)
else
  rom="$1"
fi

if [[ "$1" == *"/ti99_cart/"* ]]; then rom="$(basename "${1%.*}")"; fi

if [[ "$core" == *"mame"* ]]; then
  filename="${rom##*/}"; basename="${filename%.*}"
  ${core} "${rom}" -skip_gameinfo -snapname "${basename}"
  exit
fi

if [[ "$core" == *"libretro"* ]]; then
  retroarch -L ~/.config/retroarch/cores/${core}.so "${rom}"
else
  ${core} "${rom}"
fi

if [ -z "$core" ]; then
  ark "$1"
fi
