name: Gamelists updater

on:
  schedule:
    # Every Sunday at 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: bash update.sh
